### ISSUE TITLE
Suggested fix for a lot of things.

### ISSUE THREAD

**Issue by pheonix99** [Truinto/DarkCodex#1]
I'm seeing a sea of inaccessable call issues in the log.

You can probably fix some of that with these instructions: https://github.com/spacehamster/OwlcatModdingWiki/wiki/Publicise-Assemblies

**Comment by Truinto** [comment]
Can't see any issues in my log. Please tell me your OS and share your log.

**Comment by pheonix99** [comment]
Windows 10,
[DarkCodex] Loading Dark Codex
[DarkCodex] Loading General.patchAngelsLight
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.UnitLogic.Mechanics.Components.ContextRankConfig:m_Type' is inaccessible from method `DarkCodex.Helper:CreateContextRankConfig (Kingmaker.UnitLogic.Mechanics.Components.ContextRankBaseValueType,Kingmaker.UnitLogic.Mechanics.Components.ContextRankProgression,Kingmaker.Enums.AbilityRankType,System.Nullable`1<int>,System.Nullable`1<int>,int,int,bool,Kingmaker.EntitySystem.Stats.StatType,Kingmaker.Blueprints.BlueprintUnitPropertyReference,Kingmaker.Blueprints.BlueprintCharacterClassReference[],Kingmaker.Blueprints.BlueprintArchetypeReference[],Kingmaker.Blueprints.BlueprintFeatureReference,Kingmaker.Blueprints.BlueprintFeatureReference[])'

[DarkCodex] Loading Items.patchArrows
[DarkCodex] Loading Items.patchTerendelevScale
[DarkCodex] Loading Mythic.createLimitlessBardicPerformance
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.UnitLogic.Abilities.Components.AbilityResourceLogic:m_RequiredResource' is inaccessible from method `DarkCodex.Mythic:createLimitlessBardicPerformance ()'

[DarkCodex] Loading Mythic.createLimitlessWitchHexes
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.UnitLogic.Abilities.Components.TargetCheckers.AbilityTargetHasFact:m_CheckedFacts' is inaccessible from method `DarkCodex.Mythic:createLimitlessWitchHexes ()'

[DarkCodex] Loading Kineticist.patchGatherPower
[DarkCodex] Loading Kineticist.patchDarkElementalist
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.UnitLogic.Abilities.Components.AbilityTargetsAround:m_Condition' is inaccessible from method `DarkCodex.Kineticist:patchDarkElementalist ()'

[DarkCodex] Loading Kineticist.createKineticistBackground
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Classes.Selection.BlueprintFeatureSelection:m_AllFeatures' is inaccessible from method `DarkCodex.Kineticist:createKineticistBackground ()'

[DarkCodex] Loading Kineticist.createMobileGatheringFeat
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Facts.BlueprintUnitFact:m_Icon' is inaccessible from method `DarkCodex.Kineticist:createMobileGatheringFeat ()'

[DarkCodex] Loading Kineticist.createImpaleInfusion
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Facts.BlueprintUnitFact:m_DisplayName' is inaccessible from method `DarkCodex.Kineticist:createImpaleInfusion ()'

[DarkCodex] Loading Witch.createIceTomb
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Facts.BlueprintUnitFact:m_DisplayName' is inaccessible from method `DarkCodex.Witch:createIceTomb ()'

[DarkCodex] Loading Hexcrafter.fixProgression
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Classes.LevelEntry:m_Features' is inaccessible from method `DarkCodex.Helper:RemoveFeature (Kingmaker.Blueprints.Classes.BlueprintArchetype,int,Kingmaker.Blueprints.Classes.BlueprintFeatureBase)'

[DarkCodex] Loading General.createAbilityFocus
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.JsonSystem.BlueprintsCache:m_LoadedBlueprints' is inaccessible from method `DarkCodex.Resource/Cache:Ensure ()'

[DarkCodex] Loading Kineticist.createExtraWildTalentFeat
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Classes.Selection.BlueprintFeatureSelection:m_AllFeatures' is inaccessible from method `DarkCodex.Kineticist:createExtraWildTalentFeat ()'

[DarkCodex] Loading Witch.createCackleActivatable
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Facts.BlueprintUnitFact:m_Description' is inaccessible from method `DarkCodex.Witch:createCackleActivatable ()'

[DarkCodex] Loading Rogue.createExtraRogueTalent
[DarkCodex] [Exception] FieldAccessException - Field `Kingmaker.Blueprints.Classes.Selection.BlueprintFeatureSelection:m_AllFeatures' is inaccessible from method `DarkCodex.Rogue:createExtraRogueTalent ()'

[DarkCodex] ManualPatch DarkCodex.Patch_AllowAchievements
[DarkCodex] Finished loading Dark Codex

**Comment by Truinto** [comment]
Totally my fault. Should have tested better. I just released a new build that will work.
