### ISSUE TITLE
Suggestion: Enegize Weapon and Kinetic Fist Infusions

### ISSUE THREAD

**Issue by RanieriMatos** [Truinto/DarkCodex#100]
Hello!

I know that those infusions are, probably, the least favorite from all of the kineticist options. But they open a lot of possibilities (Energize Weapon the most) on kineticist builds. I used to play a ranger like kineticist with a bow and Energize Weapon on pen and papper, and Kingmaker (I'm not sure if those where present in the development of the game or where added by a mod). Kinda felt a little disapointed when I realized that neither where in the Wrath of the Righteous.

Links to the abilities:

https://www.d20pfsrd.com/alternative-rule-systems/occult-adventures/occult-classes/kineticist/infusion-wild-talents/#Energize_Weapon

https://www.d20pfsrd.com/alternative-rule-systems/occult-adventures/occult-classes/kineticist/infusion-wild-talents/#Kinetic_Fist

Tnks for your time and effort!

**Comment by Truinto** [comment]
That was part of Call Of The Wild mod. And you are right these features are hated from most people. I can see why. It's kinetic blade, but does 1/3 of its damage for the same burn. The only advantage it lasts until your next turn, so you can make AOO. But kinetic whip does that better.

I am curious, how do these options appeal to you? Is there some secret interaction?

Currently looking for a way to make the element selection without needing to duplicate for each element.

**Comment by RanieriMatos** [comment]
Well, Energize Weapon, for exemple, could be used with bows and benefit from all the bow feats (rapid shot, many shot, etc) or with high crit-chance weapons to add a lot of damage. Its like a flaming, frost or shocking enchantments, but with 4 times more power (these enchantments stack with the blast as well).
They benefit from the weapon enchantments, making a lot easier to land some hits, as well for keen, speed, etc.
And, since this is not subjected to spell resistance (like the normal energy blasts), turns out even better.

For Kinetic Fist is basicaly the same, for monk-like characters.

**Comment by Truinto** [comment]
I probably need to find better icons.... :P

**Comment by RanieriMatos** [comment]
You're just awesome!
I've noticed that it's possible to keep shooting, even when the maximum burn is reached. This happens with simple and composite blasts as well.

Thanks again man!

**Comment by Truinto** [comment]
It will stop applying substance infusions or metamagic, if you cannot spend the burn.
Assuming you are level 5, the form infusion is free anyways.
But I guess I can also remove the damage.

Btw, does it gather automatically? It probably only works manually...
