### ISSUE TITLE
Expanded Elements feat breaks apart Expanded Elements kineticist feature

### ISSUE THREAD

**Issue by Nerin3** [Truinto/DarkCodex#101]
Disclaimer: I'm using Kinecisit Elements Expanded mod, but I saw you posting on mod's github page, so I decided to post about this here.
That's how it looks without patch enabled:
![image](https://user-images.githubusercontent.com/1911661/181499409-c19d2374-a15b-4954-9246-266b7f253a95.png)
That's how it looks with the patch enabled:
![image](https://user-images.githubusercontent.com/1911661/181500640-e7dcff15-42eb-47a6-98df-5c23fdb23a9c.png)

**Comment by Nerin3** [comment]
It's like on the first screenshot when you pick your first element, but every other is like the second screenshot and I'm not talking about the extra feat that your patch adds, just the feature that is already implemented in kinecisist.

**Comment by Truinto** [comment]
This patch removes unnecessary complexity from the base implementation. So instead of picking "elemental focus", you just pick what blast you want. This doesn't go well, when another mod injects new foci again. I need to see what I can do.

**Comment by Nerin3** [comment]
Well I don't think it's unnecessary complexity, it's just implementing it so it's like tabletop in how it works, since you first choose the element and then you choose blast associated with the element

**Comment by Truinto** [comment]
And then the wild talents check if you have the first earth focus, the second earth focus, the third earth focus, the first air focus, the second air focus, or the third air focus.
Checking for metal alone becomes "first earth focus && second earth focus || first earth focus && third earth focus".

It's also just one example. Every blast has it's own progression line granting that element's specific element feature every other level. Even tho that feature rank level is never used.

**Comment by Truinto** [comment]
fixed
