### ISSUE TITLE
Suggestion : Insightful Contemplation mod

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#102]
Hello again !

Ok this one would be purely personnal if not far stretch balance wise :

Would it be possible to alter Court Poet Insightful Contemplation by adding to it the same scaling moral bonus to Wisdom than to INT/CHA and suppress the will save bonus altogether?

The Will bonus would be weaker but it would allow a very rare bonus to wisdom that do not exist othewise (except instinctual rager).

**Comment by Truinto** [comment]
This is too fringe for me. Sorry.

**Comment by Mythalar** [comment]
No prob, I tried!
