### ISSUE TITLE
Equiping the item "Elemental Catalyst" causes strange behavior after loading savegame.

### ISSUE THREAD

**Issue by Aberlolz** [Truinto/DarkCodex#105]
- After equiping the "Elemental Catalyst" with my Kinetic Knight, saving the game and loading the savegame, my [Character will be naked](https://imgur.com/nNzCDUM) despite wearing gear.

- [Hovering over the Character in the world causes nothing to happen](https://i.imgur.com/gb8uL04.png). Here is what [is supposed to happen if you hover over a Character](https://i.imgur.com/HeJBNVv.png). This also prevents the Character who is equipped with the "Elemental Catalyst" to be selectable by clicking on the Character, instead one has to click on the Portrait of the Character.

Version of Dark Codex used: [1.3.20]
Version of the Game:  [1.3.7d]

**Comment by Truinto** [comment]
Oh... that's what caused this... No idea how that happens. I bet there is a null exception somewhere.
I recommend you to roll back a save that doesn't have this item. I will make it unavailable/hidden.

**Comment by Aberlolz** [comment]
From what i've seen unequipping the Item, saving and reloading seems to fix it, but i can't look under the hood of the game, so i reverted to an older savegame anyway already.

**Comment by Truinto** [comment]
It won't show up in shops anymore and the special properties have been removed. Was useless after you get composite blasts anyway. Sorry for the trouble. Seemed to work fine at first glance.
