### ISSUE TITLE
elemental scion bugs

### ISSUE THREAD

**Issue by templer10** [Truinto/DarkCodex#106]
hi - a few bugs.

1) composite blasts dont use the increased Dice - for example - the simple blast (at level 9) uses D8's the composite blasts use D6's.
2) not sure if it's mod related - selevetive metakinesis doesnt work - tried it with wall and it still hurts party members.

**Comment by Truinto** [comment]
The feature reads "simple blast". Composite blasts don't fulfill that condition.
At level 15 you get d10 simple and d8 composites.

Selective doesn't work with 3rd party elements, yet.
