### ISSUE TITLE
About Magus Spellstrike ability

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#107]
When use the feat：Quicken Spell with ray spell，magus can not correctly use the Spellstrike ability. Magus only use the spell with out Spellstrike. It is not the bug in DarkCodex, i think it is bug in game.
if it is not too much trouble, could you fix it?

**Comment by knightddk** [comment]
> 

Oh，i mean the Eldritch Archer‘s spell strike ,it works with ray spells

**Comment by Truinto** [comment]
Can you provide screenshots of the scenarios? Quicken spell/normal spell.
Going to need the combat log.

**Comment by knightddk** [comment]
**woljif with  Eldritch Archer , he has the feat quicken spell**
![瞬发法术](https://user-images.githubusercontent.com/59077174/183582803-67ba911e-1410-462c-a172-71ee468a9eab.png)
**the spell has the quicken spell and not** 
![无瞬发的射线](https://user-images.githubusercontent.com/59077174/183582987-8a26918d-d229-4e37-8cd8-4bd261d203a6.png)
![有瞬发的射线](https://user-images.githubusercontent.com/59077174/183583027-5d5a17d2-e786-48cf-b236-6820c1bc9d62.png)
Use the quickened spell, woljif only use the ray attack the monster
![瞬发1](https://user-images.githubusercontent.com/59077174/183583155-67b0043e-abe8-4b5a-a122-83c9728ab101.png)
![瞬发2](https://user-images.githubusercontent.com/59077174/183583186-d909df67-cbb7-4e9d-acd3-b398b8a9c8b5.png)
Use the normal spell，woljif use his spell strike attack the monster
![无瞬发1](https://user-images.githubusercontent.com/59077174/183583532-ec98f8fe-db88-4e9e-88e5-1cbe06385b2d.png)
![无瞬发2](https://user-images.githubusercontent.com/59077174/183583577-36e6c9bd-d818-4b02-b318-ffb7bb88c71a.png)

**Comment by Truinto** [comment]
Was really hard to find out what causes this. But is really easy to fix. In short, it allows only spells with a casting time of standard action or full round to be spellstriked. I assume it's because of the special animation that's used. No matter, I overwrote that bit.
Would you mind testing it out for me?

**Comment by knightddk** [comment]
> Was really hard to find out what causes this. But is really easy to fix. In short, it allows only spells with a casting time of standard action or full round to be spellstriked. I assume it's because of the special animation that's used. No matter, I overwrote that bit. Would you mind testing it out for me?

No problem, thanks your work.

**Comment by knightddk** [comment]
> > Was really hard to find out what causes this. But is really easy to fix. In short, it allows only spells with a casting time of standard action or full round to be spellstriked. I assume it's because of the special animation that's used. No matter, I overwrote that bit. Would you mind testing it out for me?
> 
> No problem, thanks your work.And what shall I do?

**Comment by Truinto** [comment]
I thought that would be obvious. Load the update and cast a quicken scorching ray to see if it works now.

**Comment by knightddk** [comment]
> I thought that would be obvious. Load the update and cast a quicken scorching ray to see if it works now.

I try it and it works but not correctly.However, in addition to spell strike, the character will also make additional full round attacks at the same time.During the turn, if a character cast a spell again, he will not cast the spell and will not make an action.

**Comment by knightddk** [comment]
> > I thought that would be obvious. Load the update and cast a quicken scorching ray to see if it works now.
> 
> I try the quicken spell and it works but not correctly.However, in addition to spell strike, the character will also make additional full round attacks at the same time.During the turn, if a character cast a spell again, he will not cast the spell and will not make an action.

**Comment by Truinto** [comment]
Okay, I can see I missed some conditions. I changed my code. My first test looked good. Can you confirm that it works now as intended?

**Comment by knightddk** [comment]
It still doesn't work properly, and there are same problem before. Should I uninstall other mods, such as TTT？

**Comment by knightddk** [comment]
> Okay, I can see I missed some conditions. I changed my code. My first test looked good. Can you confirm that it works now as intended?


I found that if I only turn on spell strike, characters will use a full round of attack and spell strike when casting quicken spells(swift ray).If spell strike is turned off and spell combat is turned on, the character can normally cast quicken spells and use the remaining actions to use spells and attack the whole round.I hope it can help you fix the game's bug.

**Comment by Truinto** [comment]
The code for eldtrich archer spellstrike is all over the place. When you use a spell, it will remember the spell, do an attack action, then cancel the first call. Then when the attack is done, it will look up the remembered spell and execute it.
There are also exceptions, like it checks spell combat at one point, which I don't understand why it does.

This is a lot more difficult than I thought.

**Comment by knightddk** [comment]
> The code for eldtrich archer spellstrike is all over the place. When you use a spell, it will remember the spell, do an attack action, then cancel the first call. Then when the attack is done, it will look up the remembered spell and execute it. There are also exceptions, like it checks spell combat at one point, which I don't understand why it does.
> 
> This is a lot more difficult than I thought.

Thank you very much for your work anyway. If this is too difficult, ignore it.

**Comment by Truinto** [comment]
Another time perhaps
