### ISSUE TITLE
CodexLib Discussion

### ISSUE THREAD

**Issue by SpencerMycek** [Truinto/DarkCodex#115]
Hey, you mentioned in an issue on KineticistElementsExpanded that it would be possible to setup some kind of shared library (CodexLib) (https://github.com/SpencerMycek/KineticistExpandedElements/issues/23#issuecomment-1197253652)

On my side, I know that means I would begin contributing any changes/additions (within reason) to CodexLib, which would mainly(only) effect kineticist things
On your side, that probably means making sure I don't accidentally explode Dark Codex

I wanted to put the idea for that change somewhere static where the changes would be made here, and I also wanted to see how I might contribute to the change, to lessen your workload and such

This issue could also be used as a place to put things required to make any change in this direction happen

**Comment by Truinto** [comment]
I can't assess how much benefit each of us has with this library. You may just want to copy and update parts that are relevant for you. Would have no downside besides code duplication.

I can't think of any code you would want to change. It's probably mostly additions. Either new helpers or new components. But then again, you can just have them in your mod and donate code which you consider as universally helpful.

If you do end up using CodexLib, please make sure you read the description page. If the reference is not set to local-copy=false then any update I push will be overwritten by your mod.

I am sure you will have questions about some stuff. So yes, this thread will be fine.

You can get the dll and any notes I make here: https://github.com/Truinto/DarkCodex/tree/master/CodexLib

**Comment by SpencerMycek** [comment]
This may be a very dumb question, as I believe I understand most of the instructions except this:
How do I set the reference to "local-copy=false"

**Comment by Truinto** [comment]
When you expand the references and click on one, there will be properties in the view below. If the view isn't there, right clicking and choosing "properties" should open it.
That's how it looks: https://github.com/Truinto/DarkCodex/raw/master/resources/localcopyfalse.png

**Comment by SpencerMycek** [comment]
Thank you so much, this helps a ton!

**Comment by SpencerMycek** [comment]
What would be the best way for proposing new changes to CodexLib?

Fork and Pull Request?

**Comment by Truinto** [comment]
Whatever is most convenient to you.
