### ISSUE TITLE
1.4 patch removes action bars

### ISSUE THREAD

**Issue by HandOfCheese** [Truinto/DarkCodex#118]
Ever since the latest patch, the Dark Codex removes all action bars. Would greatly appreciate an update or a tip which function to disable to restore the bars. Thanks and thank you for a great mod!

**Comment by knightddk** [comment]
Waiting for the author to update for version 1.4

**Comment by Truinto** [comment]
The action bar is not disabled. The whole thing is crashing. Unsurprisingly when the game code is changed.
Stay on 1.3 until I had a chance to update. Bad luck if you play on Steam.

**Comment by HandOfCheese** [comment]
Oh damn, that sounds rough, good luck! Can't imagine playing my Kineticist without this mod, thanks for your great work.

**Comment by SethStormR** [comment]
Really great mod, good work! Waiting in anticipation for the next release of Dark Codex. :)

**Comment by Truinto** [comment]
I have a prerelease that works better. Better there are still bugs and something is weird about some guids. I recommend to wait before playing.

**Comment by pmabraham** [comment]
This is a wonderful mod, but currently unable to use in 1.4x as it removes the action bar (the game itself works without crashing when the mod is removed).  Thank you.

**Comment by Truinto** [comment]
My schedule is full. I hope to fix most of it next weekend.

**Comment by Red-Kai** [comment]
more info - it seems that the ui missing is related to the  arcanist spontaneous metamagic patch . the UI is back when the patch is off. unforantly for me , since that patch is much needed for me as I play with arcanist ....

**Comment by Truinto** [comment]
Thanks for the tip. I guess that makes sense. Something was changed on SpellSlots, which is used there.

**Comment by Truinto** [comment]
Not sure, I didn't have to make any additional changes and it seems fine. Perhaps I fixed it on the way... Let me know if this still happens to you. My saves work fine for now.
