### ISSUE TITLE
Buff Time Will Not Pass After Rest or Sleep

### ISSUE THREAD

**Issue by ForbAvalon** [Truinto/DarkCodex#127]
Like said above , after rest , the buff time will not pass
Before rest I have 23h59m buff , after rest I still have that much
I dont know which section cause these , but I disabled all homebrew part

**Comment by Truinto** [comment]
That's very little information you give me here. What buffs are we talking about? Is it all buffs or just some? Could you have other mods causing this?
I can't remember having any hacks that extend the buff time.

**Comment by ForbAvalon** [comment]
I found the reason.
The save I use use to installed old version of DarkCodex(1.3)
I read former save (which is a clean save) with last DarkCodex(1.4) , the buff time work well.
I think update may cause some error but a clean install will be safe.
