### ISSUE TITLE
Suggestion: Swift Hex Mythic ability?

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#13]
since classes with access to domains can get access to domain zealot to make their powerful domain abilities swift actions why not give witches an equivalent ability to improve their action economy? no clue about a good name for it tho

**Comment by Truinto** [comment]
Yeah, why not.

**Comment by TKDancer** [comment]
an alternative would be to make chanting/cackling become swift instead of hexes themselves

**Comment by Truinto** [comment]
I added the feature swift hex. Ingame name Cursing Gaze. I left out grant hexes. Since cackle is also a hex, it's probably affected too. Maybe I should exclude it? Let me know, if the feature works as intended or if there are bugs.
