### ISSUE TITLE
Feral Combat Training

### ISSUE THREAD

**Issue by shimazuhyuga** [Truinto/DarkCodex#132]
![20220912231002_1](https://user-images.githubusercontent.com/113405586/189800178-53dfb8e9-d5ac-4db1-802b-98f9c490ce8c.jpg)
![20220912231018_1](https://user-images.githubusercontent.com/113405586/189800192-4d098d0e-a6b2-4f3a-8910-f35a96bae769.jpg)
![20220912231453_1](https://user-images.githubusercontent.com/113405586/189800200-97aa6105-34f5-463f-92b7-0860041413a0.jpg)
Feral combat feat isn't working properly with claws given by Bloodrager/Dragon Disciple and Demon

**Comment by Truinto** [comment]
That feat has a lot of interactions. Can you specify what's wrong?

**Comment by shimazuhyuga** [comment]
The flurry of blows seems to still not add the extra attacks when using claws vs when using unarmed

**Comment by Truinto** [comment]
Duplicate of this https[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]://[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]github.com[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]/[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]Truinto[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]/[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]DarkCodex[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]/issues/35#issuecomment-1121095903[https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903]

Flurry does indeed not work completely. But differently than you think. Feral Combat Training never grants more attacks from Flurry. Read the original link for an in depth explanation.

**Comment by shimazuhyuga** [comment]
That explains everything 👍

**Comment by Truinto** [comment]
Mh. Somehow my phone botched that hyperlink real good. Anyway, the only changes I would make would actually reduce the number of attacks. Not something I usually do. Will need to think about this.

**Comment by Truinto** [comment]
Duplicate of this https://github.com/Truinto/DarkCodex/issues/35#issuecomment-1121095903

Flurry does indeed not work completely. But differently than you think. Feral Combat Training never grants more attacks from Flurry. Read the original link for in deep explanation.
