### ISSUE TITLE
Mythic Ability: Not a Chance 

### ISSUE THREAD

**Issue by Nerin3** [Truinto/DarkCodex#133]
Here's Idea for armor version of "Always a Chance" mythic ability.
When enemy rolls 20 and attack still doesn't exceed your AC the attack will still miss despite being a 20.

**Comment by Truinto** [comment]
What kind of AC do you plan that would cause a natural 20 to still miss? :D
I already though Always A Chance is too weak for an ability. Hence the patch to buff it.

**Comment by Nerin3** [comment]
Well... I had 52 AC on one character.

**Comment by Truinto** [comment]
Added. Please reply if not working.
