### ISSUE TITLE
Mythic Ability:  Unlock the equipment bar of Animal Companions 

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#134]
Baphomet's skill can  Unlock the equipment bar of Animal Companions ,why not use a Mythic Ability to unlock the equipment bar of animal companions to give them more power？

**Comment by Truinto** [comment]
I can't find that feature. Do you have the guid or exact name?

**Comment by knightddk** [comment]
In the old version, when Pavlovine used the ability:Baphomet_BaphometDisjunction(GUID:24511c87d62447ae80c57336a9c212a4) against animal companions.
This will clear all buffs and unlock the  animal companions's equipment bar.I think it's a bug, but it's interesting.
![c78069ecab64034f3b4fa7eaeac3793108551ddc](https://user-images.githubusercontent.com/59077174/190300593-365cf51f-d79a-4a0d-9aff-3801ae9aa268.jpg)

**Comment by knightddk** [comment]
And if remove AnimalCompanionSlotFeature（GUID:75bb2b3c41c99e041b4743fdb16a4289），Animal Companion can use equipment bar.
![image](https://user-images.githubusercontent.com/59077174/190302183-e5cebbd3-ca28-46d5-8a66-88e5ef0aa67c.png)

**Comment by knightddk** [comment]
thx your work, your mod is really good.I won't open the game without your mod
