### ISSUE TITLE
CodexLib Out of Date

### ISSUE THREAD

**Issue by SpencerMycek** [Truinto/DarkCodex#135]
I pulled down the most recent version of CodexLib.dll, and noticed a few problems after compiling and trying to run Wrath

I would get these errors:
```
[KineticistElementsExpanded] [Exception] MissingMethodException - Kingmaker.UnitLogic.Abilities.Components.AbilityShowIfCasterHasFact CodexLib.Helper.CreateAbilityShowIfCasterHasFact(CodexLib.AnyRef,bool)
System.MissingMethodException: Kingmaker.UnitLogic.Abilities.Components.AbilityShowIfCasterHasFact CodexLib.Helper.CreateAbilityShowIfCasterHasFact(CodexLib.AnyRef,bool)
  at KineticistElementsExpanded.ElementAether.Aether.CreateTelekineticBlast () [0x0001f] in C:\Users\Spenc\source\repos\Kineticist Element - Aether\ElementAether\Aether.cs:383 
  at KineticistElementsExpanded.ElementAether.Aether.Configure () [0x0000b] in C:\Users\Spenc\source\repos\Kineticist Element - Aether\ElementAether\Aether.cs:56 
  at KineticistElementsExpanded.StartGameLoader_LoadAllJson.LoadSafe (System.Action action) [0x00041] in C:\Users\Spenc\source\repos\Kineticist Element - Aether\Main.cs:171 
```
(Received this error for CreateAbilityShowIfCasterHasFact and CreateAddClassSkill)

When I recreated the Helper.CreateAddClassSkill in my own project, and called it, I had no issues, and it went on to generate the same error at CreateAbilityShowIfCasterHasFact, so I believe the issue may be that CodexLib isn't up-to-date regarding the most recent game update, but I am uncertain

Any tips?

**Comment by SpencerMycek** [comment]
Just to note: https://github.com/SpencerMycek/KineticistExpandedElements
The "Wood" branch is up to date with my changes, and is the current commit where I am receiving these errors

**Comment by Truinto** [comment]
You forgot to include the new CodexLib.dll in your mod folder.

Since your compiler had no error with this call, your reference is working. But obviously the mod will need the same DLL to run.

I recommend automating this with build events and macros. Otherwise you might forget to check.

**Comment by SpencerMycek** [comment]
I added automation to make sure CodexLib.dll will be put into the mod folder when I build, and the same error's persisted when trying to start Wrath

**Comment by Truinto** [comment]
Well, you can only get that exception, if the lib you build against and the lib executed are different.

There could also be a version issue. E.g. the latest version does not have the highest number. Or the assembly load function loads the wrong version. I made sure to always increment my version. Can't tell why that would be an issue.

I will double check later. Maybe check the file properties.

**Comment by SpencerMycek** [comment]
Would a solution be to Build CodexLib on my own system? So it can reference the correct assemblies on my machine?

**Comment by SpencerMycek** [comment]
I believe I found/understand the issue, although not what's causing it.
Somehow, my project is loading the assembly "DarkCodex" as well as "CodexLib" (printed out all loaded assemblies in the AppDomain), where CodexLib was version 1.1.1.27
I have the most recent release of DarkCodex, which has CodexLib of 1.1.1.27 instead of 1.1.1.29 (the most recent, and the file present in my mod folder)

My project has been loading the assembly in the DarkCodex mod folder somehow.
I fixed this temporarily by overwriting the CodexLib.dll in the DarkCodex mod folder, but there is still the bigger issue at play

### Related logs showing "Fixed" loaded assemblies
```
[KineticistElementsExpanded] WOTRDamageBreakdown, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] **DarkCodex**, Version=1.4.1.0, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] **CodexLib**, Version=1.1.1.29, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] DataViewer, Version=0.9.3.22233, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] RespecWrath, Version=1.6.7.0, Culture=neutral, PublicKeyToken=null
[KineticistElementsExpanded] KineticistElementsExpanded, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by Truinto** [comment]
Sorry for the wait. Was updating my projects files to Sdk="Microsoft.NET.Sdk" and encountered some issues.

I still suspect that you are missing the updated CodexLib in your mod folder. If it is there and it still doesn't load it, then it's the fault of the method EnsureCodexLib(), which is already explained here https://github.com/Truinto/DarkCodex/tree/master/CodexLib

I have done some tests with an empty mod and it seemed to load the correct file for me, no matter how I arranged it. So I can't really figure out what's going on. Can you perhaps push your source online, so I can have a look?

**Comment by SpencerMycek** [comment]
Absolutely, https://github.com/SpencerMycek/KineticistExpandedElements, check the "wood" branch

I believe the issue is somehow related to my project loading "DarkCodex" as an assembly, which loads CodexLib at v1.1.1.27, and therefore it doesn't need to load the CodexLib in my mod folder

**Comment by Truinto** [comment]
As far as I can tell do you not have references to DarkCodex. If you have, just don't.

Your csproj line 43 and line 114 have different macros defined. I think the path must be the same there.

**Comment by SpencerMycek** [comment]
So, I did a large cleanup of my csproj file
And I did some checking and realized: the AppDomain that is being checked is for the entirety of the unity project (named Unity Root Domain), so if DarkCodex loads before KineticistElementsExpanded (Which is does for me), and has a different version of CodexLib (latest release, last I checked, is 1.1.1.27, KEE is using 1.1.1.29), then the newer version is not loaded, which caused these issues, I believe

**Comment by Truinto** [comment]
Okay, I get this bug too. But I haven't figured out yet why it happens. I am sure it has worked in the past.

**Comment by Truinto** [comment]
Okay, apparently the parent directory of ``Mods\DarkCodex\`` is ``Mods\DarkCodex``.
Which means it only searches that specific mods folders. Which wasn't the intention.
Will fix.

**Comment by Truinto** [comment]
You will need to update your copy of EnsureCodexLib() as well. Sorry for the inconveniences.
