### ISSUE TITLE
About mythic ability Element Barrage

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#136]
Thank you very much for updating the game version that supports 1.4. x.

In the latest version, the Elemental Barrage can only be triggered by elemental damage of spells. Can it be recalled to the old version and triggered by elemental enchantment on the weapon or elemental damage from other sources?

**Comment by Truinto** [comment]
I didn't have the new blueprints at hand. I patched it blind. Might work, might not. Please provide feedback.

**Comment by knightddk** [comment]
> I didn't have the new blueprints at hand. I patched it blind. Might work, might not. Please provide feedback.

After a simple test, I think this function is OK.Even the ray that may cause unlimited damage in the past will not trigger a bug.
