### ISSUE TITLE
Always a Chance patch not working

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#137]
The Always a Chance patch isn't showing up in the menu, nor is it working when tested (nat 1 attack roll misses despite having it).
[combatLog.txt](https://github.com/Truinto/DarkCodex/files/9650591/combatLog.txt)
[GameLogFull.txt](https://github.com/Truinto/DarkCodex/files/9650592/GameLogFull.txt)

**Comment by Truinto** [comment]
Ups. I reorganised the patch and forgot to call it. Will be fixed soon.

**Comment by Truinto** [comment]
Fixed. Please reply if not working.
