### ISSUE TITLE
Limitless Skaldic Performance

### ISSUE THREAD

**Issue by bje259** [Truinto/DarkCodex#14]
Using bardic as an example I added this for skaldic in case you want to use or merge with bardic:

```
[PatchInfo(Severity.Create, "Limitless Skaldic Performance", "mythic ability: Skaldic Performances cost no resources", true)]
        public static void createLimitlessSkaldicPerformance()
        {
            var bardic_resource = BlueprintGuid.Parse("4a2302c4ec2cfb042bba67d825babfec");
            //var bardic_prereq = Helper.ToRef<BlueprintFeatureReference>("019ada4530c41274a885dfaa0fbf6218");

            var limitless = Helper.CreateBlueprintFeature(
                "LimitlessSkaldicPerformance",
                "Limitless Skaldic Performance",
                "Your inspiration knows no bounds.\nBenefit: You no longer have a limited amount of Skaldic Performance rounds per day.",
                group: FeatureGroup.MythicAbility
                ); // todo: icon?

            setResourceDecreasing(bardic_resource, limitless.ToRef2());

            Helper.AddMythicTalent(limitless);
        }
```

I couldn't find a related prereq bp reference so left that out (obviously added a line to the main class too to call this new method.  Up to you! just figured I'd share.

**Comment by Truinto** [comment]
I added the feature. Please review.

**Comment by bje259** [comment]
Sorry for the delay, grabbed your latest version and it looks to be working great! You even bundled it with the other setting which I think makes total sense!  Thanks!

**Comment by Truinto** [comment]
Thanks for letting me know. I was too busy to test it :)

**Comment by bje259** [comment]
No worries! Only hiccup I had was fixing my save by removing the feature I added as an example, as soon as I did that, save loaded just fine (all what I would have expected).  I'm going to try out the swift hexes too.
