### ISSUE TITLE
Making Assassin worth it

### ISSUE THREAD

**Issue by SethStormR** [Truinto/DarkCodex#141]
Hello,
I have a request for Myth feature. At current state the prestige class "Assassin" is pretty much useless as the most enemies you encountering have immunity to poison. So what about a myth feature that give the assassin to overcome poison immunity?

regards,

**Comment by Truinto** [comment]
Duplicate of https://github.com/Truinto/DarkCodex/issues/79
MagicTime has that feat already https://github.com/Stari0n/MagicTime/releases
Cheers :)
