### ISSUE TITLE
Impure Path

### ISSUE THREAD

**Issue by Nerin3** [Truinto/DarkCodex#143]
Mythic Ability:
Impure Path (Can only pick once)
It allows you to pick a the most basic feat (that you gain at 3rd level) from other mythic paths.
Single enforcing gaze from aeon. 
1 Angelic Halo effect or sword of heaven from Angel
Single Trick from trickster 
etc.

PS: Could you separate boundless injury into 2 separate option cause I like the option that boundless healing works on inflict spells, but I think the part which gives you the spells is a bit too op (especially for spontaneous casters)?

**Comment by Truinto** [comment]
FirstAscensionSelection
Need to think about this.

**Comment by Truinto** [comment]
I split the boundless healing into boundless injury.
Impure path is too much for me. The blueprints are very incomprehensible on what is what. The features are also very different in power level. It looks too wild to me.
