### ISSUE TITLE
Adding in a passive bonus for the Kitsune in human form

### ISSUE THREAD

**Issue by Nielspeterdejong** [Truinto/DarkCodex#145]
So I quite like the Kitsune, but I was hoping that their human form could also have a benefit of sorts. The kitsune true form has a bite attack for 1d6 damage, so it would be nice if their human form also had a bonus. I looked at the Pathfinder human feats: https://www.d20pfsrd.com/feats/racial-feats/ and I think the following benefit would be thematic and fitting:

**Change Shape:** "A Kitsune can assume the appearance of a specific human form of the same sex. The kitsune always takes this specific form when she uses the ability. A Kitsune in human form cannot use her bite attack, but instead she receives a +2 bonus on attack rolls made to confirm critical hits. At 3rd level, if she has a feat or feature that let's her add her Dexterity modifier instead of her Strength modifier on damage rolls with a weapon (such as Slashing Grace, Finesse Training, or Deft Strike) she can also add her Dexterity modifier instead of her Strength modifier on damage rolls with her bite. A Kitsune's bite attack counts as a finesse weapon. Changing shape is a standard action."

In addition to giving the human form a bonus to confirm critical hits, would it be possible to add in that Kitsune players with the Finesse Training or Deft Strike features, or with the Slashing Grace feat, can also add their Dexterity modifier instead of their Strength modifier on damage rolls with their bite automatically, even if their bite does not meet the requirements?

Would you be willing to make these two changes to the Kitsune? By changing the text for Change Shape and adding in that bonus for the Kitsune's human form, as well as letting their bite benefit from Finesse Training/Deft Strike/Slashing Grace. That way both forms would be viable, even in the late game.

**Comment by Truinto** [comment]
Sorry, not interested.

**Comment by Nielspeterdejong** [comment]
No problem :)
