### ISSUE TITLE
About the  new trait:Fate's Favored

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#146]
Fate's Favored:The fates watch over you. Whenever you are under the effect of a luck bonus of any kind, that bonus increases by 1.

**Comment by knightddk** [comment]
This background can now be applied to AC, AB, Saving Throw. But not applied to damage bonus.

**Comment by Truinto** [comment]
Archaeologist luck bonus to damage works. What feature do you test with?

**Comment by knightddk** [comment]
I tested again. Although the damage calculation did not show, the result did have an additional bonus.
I think this ability works normally. Thank you very much for your work

**Comment by Truinto** [comment]
Yeah, I did check the code in depth again and came to the same conclusion.
