### ISSUE TITLE
Kinetic Fist and Kineticist Elements Expanded

### ISSUE THREAD

**Issue by SpencerMycek** [Truinto/DarkCodex#147]
When using the Kinetic Fist infusion, and the KEE mod, no elements appear in the "drop down" menu from the Kinetic Fist activatable ability.

This was reported to me after I made the switch to using CodexLib, so there could be some kind of issue I've caused there.
Unfortunately, I'm not sure what it could be, since I'm only adding or interacting with elements that already exist in the Kineticist Tree

**Comment by Truinto** [comment]
You merge the lib. I specifically said that merging it will break stuff. It puts a clone into a separate namespace.
I can understand that the loading issue I caused was annoying. But I am confident it works now. So I recommend to load a single instance as explained in the project.

**Comment by Truinto** [comment]
Also running the master patch in that second merged instance will patch everything a second time. I am sure that will cause a bunch of bugs.

**Comment by SpencerMycek** [comment]
Apologies, I had forgotten the last bullet point of your CodexLib notes, and used some advice I received from the discord to fix the issues I was having, my fault.
I’ll get rid of the merging, and we shouldn’t have any issues post that point

thank you!

**Comment by SpencerMycek** [comment]
Tested and works
Apologies again, thank you for the great work on DarkCodex and thank you for all the help you've given me
