### ISSUE TITLE
Winter Witch is not able to select Ice Tomb hex

### ISSUE THREAD

**Issue by thewashingbear** [Truinto/DarkCodex#149]
Upon reaching high enough level for Major Hex selection, leveling as Winter Witch does not allow selecting Ice Tomb, whereas taking the same level as Witch allows selecting Ice Tomb. Surely Winter Witch should have access as well.

Also, the Ice Tomb DC appears to be calculated incorrectly. It's definitely not including the Intelligence modifier component of the expected 10 + 1/2 Class Level + Int Mod formula, but also has some weird interaction with Winter Witch or Elemental Foci that I haven't pinpointed such that I can't reconcile how or why I'm getting the DCs I am.

I.e., Witch 6 / Winter Witch 6, +9 Int, (Greater) Elemental Focus (Cold) would have an expected DC (if Elemental Focus and Cold Specialization apply) of 29. Actual DC in game is 19 - we're 1 short from somewhere after account for the lack of Int mod. I remember Cold Spec (and Winter Witch in general) being hopelessly broken forever, so maybe there are still bugs in WW abilities and that 1 DC discrepancy is not Dark Codex related.

**Comment by Truinto** [comment]
Missing winter hex selection. Can fix.
About DC, I use default context. I suspect that witch and winter witch levels don't stack for DC calculation. Will check.
Element specialization affects spells only. Hexes aren't spells.

**Comment by thewashingbear** [comment]
A little more context as I continue to play with it:
I think the formula being used by Ice Tomb is 11 + 1/2 Class Level. Winter Witch is counted properly toward class level. Wouldn't surprise me if this is an Owlcat hex bug, but that's the formula that explains the weird DCs I'm seeing - no Int mod included at all.
Also, both Elemental Focus (Cold) and Winter Witch's Cold Specialization do indeed apply their bonuses to the hex.

**Comment by thewashingbear** [comment]
Can confirm, Witch Winter selection works and the DC is working as expected. Thanks for the quick fix, it's much appreciated!
