### ISSUE TITLE
Purifying Channel - feature request

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#150]
https://www.d20pfsrd.com/feats/general-feats/purifying-channel/

**Comment by knk101** [comment]
Thank you so much for implementing this.
Currently it appears to be damaging all enemies in the area instead of only a single one.
 Feels great and powerful but not how the feat is written?
Okay with it if it was an intentional change ;)

**Comment by Truinto** [comment]
No, that's a bug.

**Comment by Truinto** [comment]
Fixed
