### ISSUE TITLE
Background Trait bonuses from Tabletop Tweaks not being applied

### ISSUE THREAD

**Issue by Xyrmes** [Truinto/DarkCodex#151]
Tips:
After installing Dark Codex, the Trait bonus that should be applied to background skills via Tabletop Tweaks no longer seems to work. As far as I can tell, they are marked as class skills if they otherwise wouldn't be, but the +1 isn't being added.

![BG1](https://user-images.githubusercontent.com/31435121/196317941-9996addf-8d57-4378-b025-604acc0d6201.png)
![BG2](https://user-images.githubusercontent.com/31435121/196317960-35ab8250-2814-46e9-95f6-ee0bfe327ef0.png)
![BG3](https://user-images.githubusercontent.com/31435121/196317973-2f09f1d2-c865-44b1-8f7b-732eade0239d.png)

**Comment by Truinto** [comment]
Try disable "Patch: Background Checks".
Doesn't look that would conflict, but wouldn't be the weirdest thing.

**Comment by Xyrmes** [comment]
> Try disable "Patch: Background Checks". Doesn't look that would conflict, but wouldn't be the weirdest thing.

Looks like that did the trick. And, yeah, it's still not the most unintuitive bug I've gotten from a mod.

**Comment by Truinto** [comment]
This patch is very short and just skips a crash report, should the character get the same background skill twice. Which is possible with the Additional Trait feat.
But itself it shouldn't cause this. I guess TTT has somewhere a patch that conflicts with mine. Tho I could not find it in Vek's source code.
