### ISSUE TITLE
Metamagic Adept issue at level 9

### ISSUE THREAD

**Issue by Ryz009** [Truinto/DarkCodex#154]
I'm having a small issue. When I level up from 8 to 9 the ability metamagic adept on my sorc vanishes. (The useable one I mean). I'm not quite sure why?

I was a crossblooded with secondary bloodline and mythic 2nd bloodline. So I got the breathe attack at level 9. Could that have caused an issue?

I do have TTT installed but I'm not sure if that would cause an issue.

**Comment by Truinto** [comment]
This is governed by the patch "Fix Bloodline: Arcane".
It should remove the concentration bonus (which was nonsense to replace the actual feature). And grant an activatable to speed up metamagic. This activatable is removed at level 20 and replaced with a passive.

This feature is surprisingly complicated. What ability exactly did you lose?

**Comment by Ryz009** [comment]
The activatable ability  for the metamagic speed increase. Metamagic adept. Which is odd because it worked just fine until I leveled up fro 8 to 9 so I'm baffled as to why it was lost. I wonder if my crossblooded getting the dragon breath feature caused it to bug out.

**Comment by Truinto** [comment]
Probably not. I can't think of a reason. Did you save and reload? Sometimes that does wonders.
Also what happens if you grant this feature again with Toybox? Does it vanish again?
Look for MetamagicAdeptActivatable

**Comment by Ryz009** [comment]
Yeah saving and reloading is one of the first things I tried because this game just bugs out sometimes XD I'll try to give it to myself with toybox and see if that helps. 

https://imgur.com/gallery/Yh1uAef is what I mean

**Comment by Truinto** [comment]
No charges means you are also missing the resource to cast. Which is MetamagicAdeptResource.
Both should be granted by BloodlineArcaneCombatCastingAdeptFeatureLevel1. Check if you have that feature.

**Comment by Truinto** [comment]
Some components (like AddFacts) check consistency upon level up. They can add or remove features that were changed. So this could happen if the base blueprint is changed or a mod modifies it. But I cannot find anything on this feature.

I will need to check if this is repeatable. If so, it would need a bug fix.

**Comment by Ryz009** [comment]
I'll let you know if this happens again on this character.

**Comment by Truinto** [comment]
Please open this again, should this persist.
