### ISSUE TITLE
Spell Perfection is not counting all Metamagic feats towards its prerequisite

### ISSUE THREAD

**Issue by thewashingbear** [Truinto/DarkCodex#155]
From the SRD, all Metamagic feats are supposed to count toward fulfilling the prerequisites for Spell Perfection, but only a subset actually are. I have Rime, Elemental, and Persistent, but Spell Perfection is not selectable on level-up. Perhaps this is caused by/does not account for interaction with TTT as Rime and Elemental are added from there.

![image](https://user-images.githubusercontent.com/107136016/196511773-e15bb8de-11e1-4341-b63c-67bb8bb94b4c.png)

**Comment by Truinto** [comment]
I have a single missing line of code which causes it to not iterate through the base game blueprints. Easy fix.

**Comment by thewashingbear** [comment]
Looks like that did the trick. Properly counting base-game metamagics now!
