### ISSUE TITLE
Spell Perfection does not double feat bonuses to selected spell

### ISSUE THREAD

**Issue by thewashingbear** [Truinto/DarkCodex#158]
I've only tested Spell Focus and Elemental Focus, but Spell Perfection is not increasing the bonus DC from these feats. I assume the same is true of Spell Penetration and Weapon Focus, but have not tested those. It does appear to correctly allow for the application of a free metamagic however.

**Comment by Truinto** [comment]
I guess that happened with the 2.0 update. Will need to check a lot of stuff.

**Comment by Truinto** [comment]
Tested Spell Perfection (Fireball) with Elemental Focus (Fire). Works as intended. Perhaps it's a more specific issue? Maybe another mod messes with it. Let me know, if you figure more out.

**Comment by thewashingbear** [comment]
You're absolutely right - chances are good that some other mod is conflicting. I turned off everything but DarkCodex and Toybox and it works as expected. Sorry for the inaccurate report. I'll post here if I find out more about what was causing the problem.

**Comment by Truinto** [comment]
I change the modifier type to ModifierDescriptior.Feat. So any mod that change that into something else would cause this. Except for TTT, which I use myself and wrote compatibly code.
