### ISSUE TITLE
Not A Chance mythic ability makes character invulnerable

### ISSUE THREAD

**Issue by hubeli** [Truinto/DarkCodex#159]
I picked Not A Chance as my lvl 1 mythic feat and since then I am only getting hit via splash damage. Any direct hit will always result in a miss. I assume this is not trhe intended behavior.

![image](https://user-images.githubusercontent.com/24227850/197330474-9e7a7158-8cd7-4427-9415-4a5429127358.png)

![image](https://user-images.githubusercontent.com/24227850/197330490-b45d30a6-007a-415f-b3d1-e245eb6eb47d.png)

![image](https://user-images.githubusercontent.com/24227850/197330548-d0c7bd43-8c40-442b-b3e7-11909c4b6dd6.png)

Am I misinterpreting anything>

**Comment by Truinto** [comment]
Ups.

**Comment by Truinto** [comment]
The logic was wrong. Should work now.

**Comment by hubeli** [comment]
I tested it briefly and it seems to work perfectly. Thank you very much!

**Comment by Truinto** [comment]
Thanks for the feedback. I am usually too forgetful or lazy to test small changes.
