### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by paxchristos** [Truinto/DarkCodex#16]
First off, thanks for the fantastic mod, I love it. 

I'm playing on Linux and am trying to troubleshoot where some issues might be arising from mod or from playing on Linux and noticed that 1/3rd of my player.log file is DarkCodex, with the worst example being the line `[DarkCodex] Cast complete TrueSeeingCommunal from Nenio` repeated 2501 times. If there's anything I can do to help, let me know!

**Comment by Truinto** [comment]
:heart:

I guess that means that someone is casting true sight. 2500 isn't particular high. It becomes troublesome, if you get hundreds of megabyte of log in a couple minutes. Which has happened to me :)

I would offer to suppress the message, but I see that it's already set to debug mode only. Whatever version you are using was compiled with the debug flag. It's just more verbose. I will make sure to disable the flag for releases.
