### ISSUE TITLE
Giving unlimited uses of the light cantrip to the racial traits of the Gnome/Kitsune

### ISSUE THREAD

**Issue by Nielspeterdejong** [Truinto/DarkCodex#161]
So I quite like all your changes, but I was wondering if you could make it so that the Gnome and Kitsune their Kitsune/Gnome magic has unlimited uses of their lvl 0 spell? The spell is situational, plus it only lasts a minute. This would make it more conventient.

Also, this is an optional idea, would you consider giving foxfire to the Nine-Tailed Heir Kitsune Sorcerer? The changes Owlcat made to that feature were pretty good, but it still feels like they are missing something thematic. A few homebrew out there gave them an altered version of the Fire Domain's "Fire Bolt", such as this one: https://drive.google.com/file/d/1hNls3jEfQG-6aq1QrIsRq80jcMfmUFnp/view In addition, the kitsune were granted foxfire in Pathfinder second edition, so it does fit the race.

"Foxfire (Sp): As a standard action, you can unleash a scorching bolt of foxfire from your outstretched hand, and target any single foe within 30 feet as a ranged touch attack. If you hit the foe, the foxfire bolt deals 1d6 points of fire damage + 1 point for every two sorcerer levels you possess. You can use this ability a number of times er day equal to 3 + your Charisma modifier."

Would you consider changing the Gnome/Kitsune Magic traits like this? And optionally give the Foxfire feature to the Nine-Tailed Heir? The new spells are thematic, but you only receive them as a much higher level, making them less effective. This way they would also gain some benefits at the earlier games and in between using their spells.

**Comment by Truinto** [comment]
I don't think Gnome actually gets any light spell. Foxfire is done.

**Comment by Nielspeterdejong** [comment]
They actually do get the lvl 0 spell light when you are in the game as I recall, or that might have been due to a mod, but the kitsune does gain it as a racial spell. But thanks for adding foxfire, this does make them a lot more thematic!

**Comment by Nielspeterdejong** [comment]
Also, great idea of also tying it to their feat! I suppose you now made foxfire bonus damage scale with total level instead of sorcerer level then? If so then you should also change that in the description for foxfire.

All in all, really great work!
