### ISSUE TITLE
Make Azata's superpower "Favorable Magic" work with spell-like abilities, especially with witch Hexes!!

### ISSUE THREAD

**Issue by Wolfy339** [Truinto/DarkCodex#162]
Thanks for your efforts!!

**Comment by Truinto** [comment]
Are you sure that's not already the case? The code looks like it would work on anything.

**Comment by Wolfy339** [comment]
After your reply, I did some more testing and found out that the issue stems from "TTT-Reworks - Favorable Magic - reoccurring saves" ... after disabling it, it worked on the first save (guess as intended?) but still fails on incense fog i.e
