### ISSUE TITLE
Purifying Channel Angel Fire Apostle v1.5.4

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#165]
Purifying Channel is still targeting multiple enemies within the radius. I am unsure if this is unique to angelfire apostle channel or consistent behaviour for other classes with the channel feature as well. 

![image](https://user-images.githubusercontent.com/92350803/199232207-13b5037d-c3ec-4b2e-ad7d-d3602b1550a1.png)

**Comment by Truinto** [comment]
fixed for real

**Comment by knk101** [comment]
You are amazing 🙏
