### ISSUE TITLE
Limitless Smite

### ISSUE THREAD

**Issue by RevanStarforge** [Truinto/DarkCodex#166]
There is a mod called microscopic content expansion

https://github.com/alterasc/MicroscopicContentExpansion

which adds antipaladin class... if it's not too much of a bother, can you make it so that your limitless smite ability works with that smite too, please?

**Comment by Truinto** [comment]
I added the guids, but didn't verify. Please test and provide feedback. You can answer in this thread.

**Comment by RevanStarforge** [comment]
it works perfectly. thank you
