### ISSUE TITLE
About Zen Archer's Flurry of Blows

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#167]
In previous game versions，the additional attack given by Zen Archer's Flurry of Blows can be stacked with Rapid Shot and Manyshot.If this feature is modified, it may improve the strength of Zen archers.

Anyway, thank the author for your work. The new background is very useful！

**Comment by Truinto** [comment]
The rules specifically call out that these two feats don't work with flurry. Zen archer is also a pretty strong class. So I see no reason to fiddle with this.

**Comment by knightddk** [comment]
> The rules specifically call out that these two feats don't work with flurry. Zen archer is also a pretty strong class. So I see no reason to fiddle with this.

Sohei's  Flurry of Blows can be stacked with Rapid Shot and Manyshot.In my opinion, this completely replaces the function of Zen archer.This makes this class lose its characteristics:  a lot of attacks
