### ISSUE TITLE
Energy Channel

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#168]
https://www.d20pfsrd.com/feats/general-feats/energy-channel/

You've responded to more of my requests than I could imagine so no worries if you don't have time for this or want to give others a go :) I just think it's cool 😎

**Comment by Truinto** [comment]
The logic I wrote for Kinetic Fist and Hex Strike was really useful here. You can select which channel you want to consume for this feature and it actually applies that channels damage.

Is the logic intuitive enough to use? Or do I need to explain that in the tooltip?

**Comment by knk101** [comment]
Thank-you so much :)

I think the UI to activate the ability is very intuitive.

Current behaviour is rolling double the channel dice in addition to adding the flat damage bonus of no. of channel dice * 2

![image](https://user-images.githubusercontent.com/92350803/200150978-45a690ea-f149-431d-92d5-7f0411aeabd1.png)

**Comment by Truinto** [comment]
Oh, I misinterpreted that. Yeah, it's a bit much.

**Comment by Truinto** [comment]
Fixed

**Comment by knk101** [comment]
It was delicious to use but not entirely fair ;)
