### ISSUE TITLE
Spell - Healing Flames

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#169]
https://www.aonprd.com/SpellDisplay.aspx?ItemName=Healing%20Flames

Seems fun :)

**Comment by knk101** [comment]
Thank-you again so much for adding these. The stage is now set for a perfect Cleric of Sarenrae run :)

The damage portion doesn't appear to be functioning and the heal is applying to the evil enemy - see Bodak in screenshot. 
![image](https://user-images.githubusercontent.com/92350803/200154085-cb6c989b-1084-4a53-aeac-01b499fd7804.png)

**Comment by Truinto** [comment]
Ups, this spell always checks the main characters alignment instead of each target.

**Comment by Truinto** [comment]
Pretty sure it works now.
