### ISSUE TITLE
Game not compatible with 1.3.7d? (no toolbar)

### ISSUE THREAD

**Issue by CronosD10** [Truinto/DarkCodex#171]
Not sure if it is a bug or lack of compatibility, but my characters don't have any toolbar, meaning I can't select any spells, abilities...

![NoToolbar](https://user-images.githubusercontent.com/117524861/200124010-08f764f9-02c7-4002-b605-a6fb121d3bb9.png)

**Comment by Truinto** [comment]
No toolbar means something is crashing. What's with that game version? Current version is 2.0.3.
If you play on a legacy branch, you can only try to use older mod versions. v1.4 or older might work. https://github.com/Truinto/DarkCodex/releases/tag/v1.4.3

But it's probably best if you update the game.
