### ISSUE TITLE
Mounted Maniac not triggering for Daeran w/ Mount from Nature Second Mystery

### ISSUE THREAD

**Issue by Bezhukov** [Truinto/DarkCodex#172]
Either on his first turn (where he's staggered) or on subsequent turns I can't get it to trigger.

**Comment by Truinto** [comment]
And how is that related to me? That feature isn't added from my mod.

**Comment by Bezhukov** [comment]
Sry, is it from TTT?

**Comment by Truinto** [comment]
Yeah, I think so :P
Np.
