### ISSUE TITLE
Flame Blade 

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#173]
https://www.d20pfsrd.com/magic/all-spells/f/flame-blade/ 
flavourful :)

**Comment by Truinto** [comment]
I copied mechanics from kinetic blade. Seems to work. The icon is different than I thought and the fire glow I added doesn't show up.

**Comment by knk101** [comment]
Thanking you kindly :) 
That may well be a vanilla bug. The flaming and holy fx have been appearing inconsistently for me since the EE arrived

**Comment by knk101** [comment]
Very odd, it doesn't work with vfx Overrides from visual adjustment mod, nor do the visual effects from sword of heaven show.
Other than that it is working. Though size is affecting the dice size, though I'm not sure if this is proper or not.

**Comment by Truinto** [comment]
Well, I won't worry about sfx for now.
I can implement maximized and empowered relatively easily. Not sure about the others. Also annoying for metamagic from mods.

**Comment by Truinto** [comment]
Ah, one more thing I forgot. Does it apply spell resistance?

**Comment by knk101** [comment]
Just checked and it's not rolling against spell resistance

**Comment by Truinto** [comment]
I added a spell resistance check. I also made it a standard action. You can either select yourself or target an enemy and get a free attack with it. But I didn't have a test dummy. I really need to build a debug tool for that.

I also added Produce Flame, which may not actually work. Again, no test dummy.

Will look at sfx later.

**Comment by knk101** [comment]
Wonderful 
I'll do some test dummy work when I get home and let you know :)

**Comment by knk101** [comment]
Confirm it's now a standard action that allows a melee touch attack upon casting if an enemy is selected.

I can't see any spell penetration rolls but it's possible they are rolling in the background.

Also noticed it procs aao's but the damage doesn't appear to trigger.
I don't know if flame bade allows aoo or not.

Produce flame ability is listed in toy box level 1 and level 2 spelllist but it can't be selected
![image](https://user-images.githubusercontent.com/92350803/204083087-2540bbe9-c125-4829-8db4-4363e1310d1e.jpeg)
