### ISSUE TITLE
Flame Blade Dervish

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#174]
https://www.d20pfsrd.com/feats/combat-feats/flame-blade-dervish-combat/

The real interest is the Cha modifier to damage rolls with flame blade. Possibly +10 ft enhancement bonus to speed, +4 competance to acrobatics (mobility?) for flavour. The resistance portions appear painful to implement and are well covered by the ascendent element mythic power.

**Comment by knk101** [comment]
Thankyou so much you are amazing
I can confirm that the mobility and speed bonus are working. 
However Flame blade dervish is adding the higher of cha or wis for some reason.

**Comment by Truinto** [comment]
Druid and shaman are wisdom based classes. Why would it scale with charisma? Seems weird to me. For now I just use the highest mental score. Might change, need to think about this.

Have you tried the fire resistance part? The code looks simple. Didn't test it tho.

Also, I think about looking at Gozreh's Trident, Produce Flame, and Chill Touch. Do you know by chance if anyone else has made any of these spells?

**Comment by knk101** [comment]
That's a good point.
The basic ignore first 10 resistance works but I'm not sure about the first 30 against undead.
I can't find any undead with fire resistance.

No mods that I know of have implemented those spells.
