### ISSUE TITLE
Shield brace

### ISSUE THREAD

**Issue by CanMik** [Truinto/DarkCodex#175]
https://www.d20pfsrd.com/feats/shield-mastery-feats/shield-brace-combat-shield-mastery/

Really good feat for fighters playing with reach :)

**Comment by knk101** [comment]
I believe kurufinve on the Wotr discord has implemented this in their mod. It hasn't released yet but I understand it's not far off :)

**Comment by Truinto** [comment]
This feat boils down to wielding two handed weapons one handed. I suppose you handle it like a one handed weapon then. Like 1x strength.
Except for very specific talent combination, this is a relatively boring feat.
I am not sure how easy it is to implement. You would need to force the weapon type into one handed, but only for certain characters. You don't usually have access to the character data from inside the weapon entity.

In any case, good that kurufinve took this. Does anyone know what's the mod called?
