### ISSUE TITLE
Spell pouch/kinetic fist menus not working 

### ISSUE THREAD

**Issue by nokturnihs** [Truinto/DarkCodex#178]
Looks like the latest update broke functionality on dark codex kinetic form infusions and spell pouch pop outs. I guess TTT had some similar issues. 

Thought I'd let ya know.

**Comment by Truinto** [comment]
Thanks. I fixed it. But other mods might still cause this issue. Expanded Elements probably.

**Comment by nokturnihs** [comment]
Awesome! Thanks so much for awesome modding! Tried figuring out unity modding but it's a lot for my tired old brain...

**Comment by Truinto** [comment]
Agreed. Learning C# will take you months (if you know coding in general) or years if you start from scratch.
And starting with modding is worse. I knew C# well, am adapt in learning, and still hurt my brain learning to code this.

Anyway. Let me know if you find anything. I saw two empty ability slots, but can't think of what that it is...

**Comment by nokturnihs** [comment]
It's expanded elements. They're missing icons. Works just a GUI issue there. They didn't have "legit" Icons for the most part anyway - looks like his pull infusion isn't slotting into the infusions pop outs either but again, it functions just with a little UI hiccup.

Yeah I do code but mainly web languages and Linux specific stuff and I'm definitely rusty there. That said done a lot of modding (some older games, Bethesda stuff, lua add-ons for MMOs, etc) - mostly just customizing and patching after shit gets abandoned. C# is a whole different ball of wax and my VERY rusty C++ and limited to begin with didn't help much. I also don't really care for visual studio that much. So... Yeah bud, thanks for doing all the heavy lifting!!! You rock!
