### ISSUE TITLE
Unable to use Kinetic Whip with Tower Shield

### ISSUE THREAD

**Issue by paxchristos** [Truinto/DarkCodex#18]
Kinetic Whip gets icon goes dark as soon as you equip a tower shield, but it will keep working if you use a light or heavy shield.

**Comment by Truinto** [comment]
The correct behavior would be to always have it dark, when a shield is equipped, right? I think to remember kinetic blade cannot be used with a shield, unless you are kinetic knight. Or at least gathering doesn't work with any shield...

**Comment by paxchristos** [comment]
Both hands being free are required for most Kineticists to gather power. Kinetic Knight allows you to use Light or Heavy Shields and still gather power (in tabletop, Elemental Bastion is unfortunately not implemented.) 

Kinetic blade and Kinetic whip are both treated as one handed weapons, so off hand should not make a difference for ability to use.

**Comment by Truinto** [comment]
I will take a look at it. Getting late though

**Comment by Bahbus** [comment]
Kinetic Whip should probably also be available to a TWF Kinetic Knight while using the weapon for Kinectists in the offhand - whether it should augment just the main hand into having reach or both main and off-hand, would be up to you. I think it should basically only be greyed out if you currently don't have a Blade Infusion equipped (turned on) at all.

**Comment by Truinto** [comment]
Should be fixed with 1.1.4. Let me know if it works satisfactory.
