### ISSUE TITLE
Spell Perfection problems

### ISSUE THREAD

**Issue by Oceansoul119** [Truinto/DarkCodex#182]
Issue one: Certain spells aren't available for picking via spell perfection. Ones I've noticed specifically being the variants created by elemental bloodlines. These spells also aren't covered by picking spell perfection for the normal versions of the spell. 

Issue two: If you have more than one spellbook that could have a spell (Scorching ray for instance) then the spell perfection interface will show multiple entries for that spell making finding the spell you want a slight chore. Only really applicable for a Legend, Mystic Theurge, or character gestalted via mod though. 

To reproduce both issues at once create a Sorcerer 6/Wizard 6 character with the Air Elemental Bloodline, pick standard Scorching Ray for both halves, then choose Spell perfection: Scorching Ray and Metamagic: Bolstered.  The (electric) variant for the bloodline wont be in the Spell Perfection list to pick whilst the standard one will be there twice, it also wont be a level 2 spell with Bolstered applied unlike the standard version in both spellbooks.

**Comment by Truinto** [comment]
1) Reading between the lines; so you can pick the base spell, but it does not apply the effects. Does it apply the metamagic reduction?

2) Okay, duplicates are annoying. But selecting one version of scorching ray effects it from any spell book, right?

I don't understand how the spell wouldn't be bolstered, if you applied bolstered metamagic... or are you talking about the spell level, not the effect?

I will test it out. But creating custom code for parameterized feature selection will be challenging. There is no quick fix.

**Comment by Oceansoul119** [comment]
2: Aye selecting any of the scorching rays affects all spellbooks.

The spell is bolstered, but the level reduction doesn't apply to the variant. Sorry about not being clearer.

**Comment by Truinto** [comment]
I see. No need to apologize. Your report is already better than 80% of what I usually get :)

**Comment by Truinto** [comment]
I applied some fixes. Maybe take a look.

Btw, you can use the search to narrow down the spell you want. First select spell perfection and while it's expanded type in the spell's name in the search box.
