### ISSUE TITLE
Metamagic Traits.

### ISSUE THREAD

**Issue by DarkSonic1337** [Truinto/DarkCodex#183]
After the newest update I can pick the new spells added via dark codex with metamagic master and magical lineage, but the original spells are not available. Searching for the trait in toybox search n pick I see metamagic master with no options at all, just a grey bar. 

I rolled back to the previous release and was able to pick the old spells as normal, but not the added ones. Even was able to save and update and keep the functioning abillity.

**Comment by Truinto** [comment]
With original spells you mean all other spells? Mh... I cache the spell list. Which means my cache isn't loading the base game blueprints. Maybe the game log has the solution.

Toybox probably accesses the list by other means and doesn't call my patched selection. So it appears empty. That patch fixes other issues.

I am not surprised you can keep the abilities through updates. This is just a matter of selection, not function.

**Comment by Truinto** [comment]
Super annoying bug. Turned out that the issue was due to the parent spell being set to an empty reference. But I checked for null. I assume that the deserialization is the reason this is empty, instead of null.

Anyway, I fixed it.
