### ISSUE TITLE
Kineticist: Cannot Choose Deadly Earth Infusion with Wood Focus

### ISSUE THREAD

**Issue by Styx0420** [Truinto/DarkCodex#184]
By checking "https://www.d20pfsrd.com/alternative-rule-systems/occult-adventures/occult-classes/kineticist/infusion-wild-talents/", I suppose Deadly Earth should work with earth and wood elements. Such form Infusion shall work with associated blasts including autumn, earth, magma, metal, mud, spring, summer, verdant, winter and wood.

In game, kineticists who have wood focus cannot choose Deadly Earth as a wild talent nor can they apply Deadly Earth to any blasts related to wood element (both simple and composite ones). Can we add this form infusion for these blasts? This seeks to follow the tabletop ruleset.

Thank you for possible fix and update!

**Comment by Truinto** [comment]
Well, that's clearly not in my mod. I can see that Spencer isn't updating his mod anymore. I might continue a fork. But I need to clean up my own mess first.
