### ISSUE TITLE
Channel Form feat Ability

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#186]
The feat/associated abilities are listed in the readme and present in the code however don't appear as a selectable feat in-game. I was unable to find the feat or channel ray/line etc in toy box.

This is an amazing idea for ability change btw :) 

- screenshots
- combat log
- game log here: "%appdata%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous"

**Comment by Truinto** [comment]
Doesn't work yet. Forgot to set hidden flag, that's why it's in the auto generated readme.

**Comment by knk101** [comment]
Ok that makes sense 👍

**Comment by DaTroll** [comment]
So technically it's not even in the mod yet? It seems you can't disable it via UnityModManager settings.

**Comment by Truinto** [comment]
Set hidden. For some reason this feature doesn't want to work. Will come back to it, when I fixed other stuff.
