### ISSUE TITLE
Magical Lineage and Metamagic Master only show modded spells

### ISSUE THREAD

**Issue by ChaoticTabris** [Truinto/DarkCodex#188]
Both Backgrounds are showing only spells added by mods for selection. This includes spells from DarkCodex itself but also spells from other mods I have installed like CharacterOptionsPlus and Expanded Content.

![image](https://user-images.githubusercontent.com/10170803/205455948-4e07603d-9114-4d50-b7da-ab06354f9e98.png)
![image](https://user-images.githubusercontent.com/10170803/205456034-2b692892-708c-4686-b82c-e3c74a72478a.png)

**Comment by Truinto** [comment]
Duplicate of #183
I haven't had time to address this yet. Downgrading 1 or 2 versions will fix this; but restrict you to known spells (which was the reason to change this).
