### ISSUE TITLE
Basic freebie Feats: Point-Blank Shot

### ISSUE THREAD

**Issue by 1RMR1** [Truinto/DarkCodex#190]
Hello,

For Basic freebie feats. It looks like Point-Blank Shot is gained automatically. I understand if this is because of coding as it's a prerequisite for a lot of feats. In the Elephant Handbook, Precise Shot replaced Point-Blank Shot for all prerequisites and Point-Blank Shot is now a stand-alone feat.
Thanks for the mod!

Cheers,

**Comment by Truinto** [comment]
Yes. I didn't want to change all the prerequisites. Would also create issues with other people's mods.
