### ISSUE TITLE
Evangelist fix for Limitless Bardic Performance always fails check

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#193]
Based on the code, you seem to have used the wrong GUID when calling the EvangelistResource, so it always fails the check to see if HBA is installed. You used "973c613b8443cf14495c283e293d35f9" when you should've used "43385175fd022c546865e7b37bcc08ce". The former points instead to the generic BlueprintAbilityResource template.

**Comment by Truinto** [comment]
Thanks

**Comment by Truinto** [comment]
I changed the guid. I hope they are correct. I won't install that mod. Thanks for the detailed report.
