### ISSUE TITLE
True Dragon mythic power broke my draconic claws

### ISSUE THREAD

**Issue by Bobtritan499** [Truinto/DarkCodex#195]
After I selected True Dragon at Mythic Rank 1, I was unable to use Dragon Claws at all, and my character will default to regular unarmed attacks, rather than claw attacks

![20221227161437_1](https://user-images.githubusercont
[GameLog.txt](https://github.com/Truinto/DarkCodex/files/10311118/GameLog.txt)
ent.com/118304236/209735581-512a9de0-d0fc-49e7-8444-dadb253c31cc.jpg)
 20221227161419_1.jpg…]()
![20221227161427_1](https://user-images.githubusercontent.com/118304236/209735576-ec764742-4198-45bb-adb1-9616832394ae.jpg)
![20221227161434_1](https://user-images.githubusercontent.com/118304236/209735580-4b27a638-4122-4fdc-a23c-c2199c82ba5b.jpg)

**Comment by Truinto** [comment]
Are you sure? Because I only decrease the use cost to 0. It would be very weird to have any other effect.
I suspect this ability only works during combat. Did you test it in combat?

**Comment by Truinto** [comment]
I was right. The ability doesn't start until start of combat. I wrote a patch to start it immediately. I didn't test what happens after combat, but I assume it will stay enabled now.
