### ISSUE TITLE
Martyr Paladin qualifies for Bardic Performance feats but not Limitless Bardic Performance

### ISSUE THREAD

**Issue by Deiwos** [Truinto/DarkCodex#196]
It says it's missing the Bardic Performance feature. See: https://i.imgur.com/68lroUE.png

Additionally, if I use Toybox to forcibly give the mythic perk to the paladin, I still have a limited number of performances. See:
https://i.imgur.com/f5ctidV.png (note: 'Acquired ability')
https://i.imgur.com/m69tNwa.png (down from 31)

**Comment by Truinto** [comment]
Martyr has a unique resource id. They don't stack with other bardic songs. I added them to the pool.
