### ISSUE TITLE
Various issues with Flame Blade

### ISSUE THREAD

**Issue by Cylush** [Truinto/DarkCodex#197]
Okay, not entirely sure how the wording of the spell is meant to be interpreted, but from what I can tell ingame, Flame Blade doesn't work with *anything* that works with scimitars, including Sohei-style Flurry with Heavy Blades / Scimitars and Weapon Focus - Scimitar. The crit range is also 20, but I believe that should be the case, as Mythic Flame Blade changes that to 18-20 on pnp. If Flame Blade essentially being a stick and not a scimitar is intended, ignore this report, but otherwise it'd be incredibly nice for the weapon wielded as a scimitar to work with scimitar-based feats.

**Comment by Truinto** [comment]
I will consider it. Tho crit range is a weapon property that imo is overwritten with spell.

**Comment by Truinto** [comment]
Is this the only issue you have? Because I try to play test it right now and I don't get any weapon to spawn...

**Comment by Cylush** [comment]
I haven't tried to use it since I posted the issue, but at the time of posting my only issue was the flame blade not triggering any scimitar-related features.

________________________________

**Comment by Truinto** [comment]
I remove that message. For whatever reason it won't allow me to spawn in the weapon, if I change the weapon type. Which is really strange. I took apart the code and couldn't find why it would do that. Also no error messages.

**Comment by Cylush** [comment]
Oh, weird. Would it be possible to apply the effects of Flame Blade (hits touch AC, cha to damage with Flame Blade Dervish Combat, fire damage, etc) to a normal scimitar? I think I looked through Toybox Enchantments and couldn't see a method.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Truinto** [comment]
After countless tries... I think it's because my cleric doesn't have proficiency with scimitars.

**Comment by Cylush** [comment]
Oh my god LOL. Does giving them proficiency fix it, then?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Truinto** [comment]
There is a scope to force equip it. So it works now, even without proficiency. I don't know all the effects of this change. Weapon focus is now scimitar instead of touch attacks. It should still do touch attacks, although I had no punching bag to test it.

**Comment by Cylush** [comment]
Alright, perfect. I can do some testing with it once its released and see if it works with everything :) Thanks so much!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Truinto** [comment]
This is off-topic, but the "Get Outlook" advertising is a bit annoying. I recommend you [Fairemail](https://github.com/M66B/FairEmail). The free version can do almost everything and the pro version is really cheap.

**Comment by Cylush** [comment]
Ah, my apologies, its automatically appended to mobile posts from my email. I forgot to remove it.
________________________________

**Comment by Truinto** [comment]
So, did you have time to test it?

**Comment by Cylush** [comment]
Many apologies, life got busy for a while. I did some preliminary testing and it seemed to work fine with Improved Critical and Weapon Focus, and weapon buffs such as Oracle's level 11 elemental mysteries.
