### ISSUE TITLE
Request/Reccomendation: more limitless options

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#2]
may be a neat idea to look at some other classes to get limitless mythic ability options like Arcanists, Magus, Incense Alchemist and so on

**Comment by TKDancer** [comment]
any chance to expand the new limitless just added to include the incense ability from the incense alchemist archetype?

**Comment by Truinto** [comment]
I expanded the limitless bombs to cover incenses, too. Didn't test, please let me know.

**Comment by TKDancer** [comment]
i'll test but then i recalled paladins could use it too, thanks for the hard work so far tho!

**Comment by Truinto** [comment]
Well, most likely this feature works. Please let me know. Too lazy to try out every option. If the content table has ✔️, then I have checked it already.
