### ISSUE TITLE
Prodigious TWF doesn't count as TWF for TWF (Mythic)

### ISSUE THREAD

**Issue by starlight332** [Truinto/DarkCodex#200]
Basically what the title says.

**Comment by FrijDom** [comment]
PTWF doesn't give you TWF, it lets you take TWF with your strength score instead of your dexterity.

**Comment by starlight332** [comment]
I'm an idiot with english being my 3rd language. Thought it counts as having TWF for feats.

**Comment by Truinto** [comment]
No problem at all. I didn't even have time to read this report.
