### ISSUE TITLE
Wandering Witch Hexes apply to the user as long as they're selected.

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#202]
I don't currently have any screenshots of it (cause the playthrough I had with a Witch ended, DLC3 with Last Azlanti mode), but I noticed it because I had a random -4 on my attack rolls. Turns out, switching from Evil Eye to Fortune made it go away. Not sure on the exact causes, but it's very odd.

**Comment by Truinto** [comment]
I cannot find how I would cause this bug. I don't understand how AbilityApplyFact works. I doubt I can bug fix this.
