### ISSUE TITLE
Limitless Bardic Performance Prerequisite Bug

### ISSUE THREAD

**Issue by khoa0101** [Truinto/DarkCodex#204]
![image](https://user-images.githubusercontent.com/70730501/211236580-0c85f37d-0c06-4b61-9d58-32be0d04d519.png)
As you can see in the image above, I'm playing a Dirge Bard and I have bardic performances but I was not able to take Limitless Bardic Performance.

**Comment by Truinto** [comment]
Will fix

**Comment by Truinto** [comment]
Fixed
