### ISSUE TITLE
Chain Infusion not affected by spell resistance

### ISSUE THREAD

**Issue by Dragsis** [Truinto/DarkCodex#205]
I have noticed that the Chain Infusion doesn't allow Spell Resistance. I am unsure if this is deliberate, but since it is an energy blast, it should.

![Chain Bug](https://user-images.githubusercontent.com/33827106/211789488-2af283cf-500c-4a05-bcb9-aa0978a0d929.png)

**Comment by Truinto** [comment]
Thanks for the report. I set that value to true, but overwrote it a couple lines again. It was a bug and should work now.
