### ISSUE TITLE
Feral Combat Training Flurry

### ISSUE THREAD

**Issue by Grimword** [Truinto/DarkCodex#206]
I have a bloodrager monk, with the Abyssal bloodline. Feral combat training does not allow the use of my claws with flurry when raging. The other damages and abilities appear the same, however I only have 3 attacks when raging (with claws), and 5 attacks when not-raged (without claws)

I tried rebuilding the character using the training and toybox to toggle the feat with no positive result. 
Quickly built a feral warpriest/monk. The static claws also did not benefit from flurry of blows.

Seems that aspect of the feat does not work as written.

**Comment by Truinto** [comment]
It's the third time this topic comes up. But the first time it's not about getting extra attacks. People assume this would get them 5 weapon attacks and additionally their natural attacks.

By RAW and RAI you would get 5 claw attacks and they do get the normal BAB penalty (0/0/-5/-10/-15/-20).

**Comment by Truinto** [comment]
There are a lot of combination of features and no way to select which weapon attacks a character should do. E.g. you would be able to do 5 claw attack. Or instead 5 bite attacks.
So it's rather difficult to come up with a smart way to implement this. If you have a suggestion, I am all ears.

**Comment by Grimword** [comment]
I am sorry if I wasn't clear in my post. The issue is not _which_ weapons I use in those attacks, it is that they do not get 5 natural attacks as RAW/RAI and the feat description. The issue very much is about not getting extra attacks. I tested multiple sources of natural attacks and none worked with FCT/Flurry.

I have very little experience in coding, I understand it can be difficult to find a solution, I just wanted to make you aware of the bug.

**Comment by Grimword** [comment]
I have done a bit of playing with it, even started a new monk just to have a clean test. It does use the claws with the flurry ability now. Even reloaded the previous version. 
1.15.17:
unarmed flurry (0/0/-5/-10/-15)
FCT clawed flurry (0/0/-5/-10/-15) (0/-5/-10/-15)

1.15.15:
Unarmed flurry (0/0/-5/-10/-15)
FCT Clawed flurry (0/0)(0)

I hope this clarifies the issue. From my limited experience, I would guess the game engine is at fault for the weird interactions. I should have been more specific from the start, so I do want to apologize. I will play around with the other abilities too over the next couple days as well. I do want to add that I really enjoy your mod and want to sincerely thank you for all the work you have done.

**Comment by Truinto** [comment]
Ah... that's a lot of offhand attacks. Do you have two-weapon-fighting?

Anyway, thanks for testing and you are welcome :heart:

**Comment by Grimword** [comment]
I went through every ability/feat on the character, there is nothing that gives them additional attacks other than the high BAB at that level.
