### ISSUE TITLE
Monk Unarmed strikes damage scaling not applied to natural weapons

### ISSUE THREAD

**Issue by Eldurad** [Truinto/DarkCodex#21]
Not 100% sure if it is intended, but there seems to be an issue with the monks scaling of unarmed strikes with natural attacks when picking feral combat training. Unarmed attacks work as intended. The issue could also result in me using the weapon focus plus, expanded content or tabletop tweaks mod, but i don´t know a thing about modding so i could be totally wrong. 

Nonetheless thx for your great mod <3

**Comment by Truinto** [comment]
I checked the code and cannot see a connection to that. The only thing I could think of is a class/feat that change weapon damage that originally would apply to non-unarmed weapons. Like say "Improved Claw: Deal 1d8 damage", which then overwrites the monks unarmed attacks.

I can't think of any real feats that do that. I will not look for the needle in the hay stack. Maybe you can check your build for features like that. If you figure out what causes it, I will happily patch the issue.

**Comment by Eldurad** [comment]
Ok thx anyway thought maybe you would have an idea what it could be will check my build.
Keep up the great work :D
