### ISSUE TITLE
Inspire Rage freezes character in combat

### ISSUE THREAD

**Issue by nharwell** [Truinto/DarkCodex#212]
I've ran into a strange problem.  My kinetic knight locks up in combat if under the effects of Inspire Rage from a skald.  His action bar blanks and I can't even end his turn with the space bar. I have to switch to RT mode and play the combat out without him.  When Inspire Rage expires everything returns to normal and he can act.

I've tested this in 2 different games now - in both the main campaign and Midnight Isles.

**Comment by Truinto** [comment]
Sounds like a crash. Restart the game, load the save, trigger the bug, then force close the game. That way the log has the most useful information. Post here the full game log and player log.

**Comment by nharwell** [comment]
In both cases uninstalling and reinstalling, then respecing the character seemed to fix the issue.

**Comment by Truinto** [comment]
It's very unlikely reinstalling does anything at all. Deleting the config file might help, if you had disabled some patch that was required.
I assume respecing does clean up the unit components, so that might help. But without further information I can't search for the problem.

**Comment by Deiwos** [comment]
Hi sorry to reopen this but I'm also experiencing this problem. If I allow my Kineticist to accept Inspired Rage, attempting to attack in Turn-Based just causes the character to lock up unable to do anything unless I go into Real-Time and either tell her to do something else or turn off accepting the rage.

See:
https://i.imgur.com/kQ6IIqG.jpg
https://i.imgur.com/0qXwGUO.jpg

Additionally, if I try to attack in Real-Time mode while I'm accepting rage, I just stand there spamming some effect 10 times a second and it looks like this: https://i.imgur.com/T4L1epm.jpg

It's an aside but Blade Rush being a spell that is disabled by Inspired Rage is pretty sad too, heh.
