### ISSUE TITLE
Cannot select Limitless Bardic Performance on Thundercaller

### ISSUE THREAD

**Issue by Prizzels** [Truinto/DarkCodex#215]
X Bardic Performance
v Bardic Performance

I see this under requirements ultimately making it unselectable. When browsing similar mythic abilities, none have this double requirement text. 

Afaik also applies to  Sensei but worked fine for Skalds.

**Comment by Prizzels** [comment]
Is it possible that a game started with a previous version would carry it over? I'm doing DLC runs and have Codex fully updated but I guess its technically one save.

**Comment by Truinto** [comment]
Nope. This will instantly updated and is not stored in the save file. This is a duplicate of  #204
I am very confused on how it wouldn't work.

**Comment by Truinto** [comment]
![pic](https://user-images.githubusercontent.com/47917181/222925231-91d790d9-c09c-4877-8427-589a365e70ec.jpg)
No idea what's going on your end. If you find a lead, let me know.
