### ISSUE TITLE
Flame Blade Dervish Combat feat prerequisite  

### ISSUE THREAD

**Issue by nixgnot** [Truinto/DarkCodex#216]
Not sure is this WAD.
https://www.d20pfsrd.com/feats/combat-feats/flame-blade-dervish-combat/
FBDC have a prerequisite  that you should can cast Flame Blade (its not mentioned on the ui but it should be)
HOWEVER, now you can only learn FBDC while you have Flame Blade in your initial spell list, which means only Druid and Shaman
you CANNOT learn FBDC while you get Flame Blade from other way -- such as,  you get FB from Loremaster's Secret -- 
which is legal according the tabletop rule, IMO.

Sth more, Flame Blade Dervish Combat should be a COMBAT FEATS
but its not included in the Combat feats list in the game now, so you cant choose it as a bonus combat feat for fighters, or Loremaster's Secret - combat feats

**Comment by Truinto** [comment]
Forgot about it being a the combat feat. Will update next time.
