### ISSUE TITLE
Can't open skill tab, action tab and belt tab

### ISSUE THREAD

**Issue by khoa0101** [Truinto/DarkCodex#218]
I can't open the tabs located on top of the action bar when I have the mod enabled. I can't cast spells or do anything besides basic attacking for combat.

**Comment by Truinto** [comment]
I have the suspension it's Toybox.

**Comment by Truinto** [comment]
I just confirmed it. This assembly works
[ToyBox.zip](https://github.com/Truinto/DarkCodex/files/10924499/ToyBox.zip)
