### ISSUE TITLE
Spell Perfection requirements don't include modded metamagic

### ISSUE THREAD

**Issue by LightOfCentury** [Truinto/DarkCodex#222]
Spell Perfection seems to require one of a specific list of feats as opposed to accepting any three metamagic feats as prerequisites. This makes it more difficult to acquire for those who want modded feats from TabletopTweaksBase like Encouraging Spell, Intensified Spell, Piercing Spell, etc. Spell Perfection also fails to double the effects of these feats, although that's somewhat understandable.

**Comment by Truinto** [comment]
Took me some effort to figure out why TTT's features won't show up for me. Turns out Vek loads blueprints before the game does, which I thought would be a no-no.
