### ISSUE TITLE
a graphic issue caused by flame blade

### ISSUE THREAD

**Issue by nixgnot** [Truinto/DarkCodex#224]
character will become nude and wield nothing after you load a game which saved while you wielding flame blade 

![20230313000806](https://user-images.githubusercontent.com/20860979/224559928-a97854d3-5230-41f3-839e-0d651b0171ea.png)

**Comment by Truinto** [comment]
That was a coincidence. That bug existed long before I coded Flame Blade. But it does seem to be a bug in this mod. I just don't know when, how, or why this happens. I have no clue where to start looking. I don't think I can fix it.

**Comment by Truinto** [comment]
The only good thing is that if reequip your armor will appear normal again. As far as I can tell it only affects the main character. Let me know, if you figure out anything else.

**Comment by Truinto** [comment]
You are right. Didn't think there would be another bug that cause this. The whole thing is weird, because I copy the spell weapon logic of kinetic blades for this. Anyway, I patched it and it will work with the next patch.
