### ISSUE TITLE
Question for localization

### ISSUE THREAD

**Issue by nixgnot** [Truinto/DarkCodex#225]
Hi here. I'm trying to add Chinese localization for this mod
However i found TONS of texts which have key just like "enchant#***" : "xxx" in enGB.json
while *** is the key and xxx is the item description , which is included in the game's localization files.
they have same key except the enchant# prefix, and different link format.

so what does these text used for?
and is it necessary for translate it? there are really SO MANY TEXT lol

**Comment by Truinto** [comment]
Hi. No, not necessary. There is an option to show all hidden enchantments (weapons, armor, etc). Since these have no display names, they use their I'd and can be renamed in the localization file. But if you don't see them otherwise. Disable 'name all'.

BTW, I haven't tried any translation. So the process might not work or is confusing. And text in the mod menu is fixed. So I will need to optimize a bit for you.

**Comment by nixgnot** [comment]
oh TY for reply.
other feats and spell texts which i translated works properly now~
I'll let you know if i met other issue~

**Comment by Truinto** [comment]
I just noticed that only the enchantment descriptions are marked with enchant#. But the enchantment name is not. I should be able to fix this to reduce the amount of text needing translation further.

**Comment by Truinto** [comment]
Just know that I will save all the enchantment based strings into its own file. That should make translating a lot easier. I am also writing a small tool to make updating the translation file possible (without need need of manually sorting through all lines).

**Comment by nixgnot** [comment]
> Just know that I will save all the enchantment based strings into its own file. That should make translating a lot easier. I am also writing a small tool to make updating the translation file possible (without need need of manually sorting through all lines).

yeah thank you！
in fact i already finished the translate
and doing test....

i found that enchant# strings (enchantment descriptions) will not used in the game?
at least it just read these localized strings from the origin game here.....
i just translate these enchantment names and other spells/feats, and looks like that all thing works properly.....

**Comment by Truinto** [comment]
I update the language file. Here is also the small program to make updating the json file easier. It will filter through any changes. I wrote a small readme, but I don't think you will need it.
https://github.com/Truinto/DarkCodex/raw/master/LocalizationApp/LocalizationApp.exe

**Comment by nixgnot** [comment]
> I update the language file. Here is also the small program to make updating the json file easier. It will filter through any changes. I wrote a small readme, but I don't think you will need it. https://github.com/Truinto/DarkCodex/raw/master/LocalizationApp/LocalizationApp.exe

oh thankyou! 
ill update the locale file to fit the update.

**Comment by Truinto** [comment]
Do you want me to publish the file? Or how does this work?

**Comment by nixgnot** [comment]
> Do you want me to publish the file? Or how does this work?

yeah it works here and at some friends of me
shall i  send pull request for include the locale files?if so which dir should i place it in?
havnt see locale files here :p

**Comment by Truinto** [comment]
https://github.com/Truinto/DarkCodex/tree/master/DarkCodex/Settings
Can you not share files in this comment section? Not sure if you need write access for that.

**Comment by nixgnot** [comment]
> https://github.com/Truinto/DarkCodex/tree/master/DarkCodex/Settings Can you not share files in this comment section? Not sure if you need write access for that.
look like i dont have  access  to upload the files. so i sent a pull request
you can just merge that :P

**Comment by Truinto** [comment]
Thanks for your contribution. Translation is never really finished. If you want to update your translation, is there anything I can do to make it easier for you?

**Comment by Truinto** [comment]
I can automate to pull files from any URI. So you could make a new repository to upload your file and I will download them from there. Does not have to be a fork. I just need to know where to look.

**Comment by nixgnot** [comment]
> Thanks for your contribution. Translation is never really finished. If you want to update your translation, is there anything I can do to make it easier for you?

yeah nevermind , i think you already do so much for that localization
the only thing is some of the keys will changed after the mod updated, it will be more convenience if we can avoid this -- but nevermind this  if it is some sh*t because of the owlcat -- i know nothing about make a mod --and its not too hard to replace them by tools 

i ll make a repository to save the updated localization file, and let you know when you have a update

**Comment by nixgnot** [comment]
> Thanks for your contribution. Translation is never really finished. If you want to update your translation, is there anything I can do to make it easier for you?

yeah nevermind , i think you already do so much for that localization
the only thing is some of the keys will changed after the mod updated, it will be more convenience if we can avoid this -- but nevermind this  if it is some sh*t because of the owlcat -- i know nothing about make a mod --and its not too hard to replace them by tools 

i ll make a repository to save the updated localization file, and let you know when you have a update

**Comment by nixgnot** [comment]
> I can automate to pull files from any URI. So you could make a new repository to upload your file and I will download them from there. Does not have to be a fork. I just need to know where to look.

hi here. i set a new repository to upload/update the locale files here, and include some new fix.
https://github.com/nixgnot/WOTR-CONTENTS-MODS-CN/tree/main/DarkCodex%E6%B1%89%E5%8C%96
