### ISSUE TITLE
Mobile Gathering Doesn't Appear to Work

### ISSUE THREAD

**Issue by Valdacil** [Truinto/DarkCodex#228]
DarkCodex 1.5.23
Kineticist [Psychokineticist] Level 7; Infusion Specialization 2 + Mobile Gathering
Steps to Reproduce:
1) Click Mobile Gathering [Move] ability
2) The screen flashes black for a second, but then shows the kineticist with swirling energy around her as if she gathered
3) Move up to before point where it would use the standard action
4) Enabled Empowered Metakinesis
5) Both regular and extended range show a cost of 1 as if I hadn't gathered power
6) Click to use blast, shows accepting 1 Burn (and increments burn count)

![20230317221623_1](https://user-images.githubusercontent.com/29554714/226086384-a8d218ff-6dd1-4167-9e4a-61d0a65816ee.jpg)

**Comment by Truinto** [comment]
I tested it. No black flash and the cost is calculated correctly. Either your setup is more complex or you have both "Patch: True Gather Power Level" disabled AND not set your gather power level toggle to whatever you want.
