### ISSUE TITLE
Arcane Reservoir and BubbleBuff

### ISSUE THREAD

**Issue by Zane-Sutton** [Truinto/DarkCodex#236]
It appears the "Limitless Arcane Reservoir" Mythic feat is having some issues with the BubbleBuff mod. My brownfur transmuter is able to apply multiple transmutation feats, such as low-level share transmutation long arm and powerful change owl's wisdom, but seems to stop and throw errors after about 8 or so of these spells are cast, erroring out on my mass powerful change bull's strength and frighful aspect.

I have already put a message on the bubblebuff page, but thought I would post it here. I'm just guessing here but i'm wondering if these limitless feats don't actually internally change the amount of charges these abilities have, it just sets a flag that makes them infinite or something similar. and bubblebuff reads this original unchanged value and fails to apply all your buffs because of it

If that is what's going on, requesting the charges be set to 9999 or something so this doesn't happen

![image](https://user-images.githubusercontent.com/33303277/229350120-c1743466-e8a4-4fd9-987b-a8d2104ebd24.png)

**Comment by Truinto** [comment]
There are features in base game which reduce the cost per use to zero. This makes them infinite. I use the same mechanic for the limitless feats. While I could increase the charges, it's tedious to change that code. And also these base game abilities would still have this bug. So it makes little sense to me.

Btw, there are also abilities that use more than 1 charge. BubbleBuff would discount them, if this bug stays.
