### ISSUE TITLE
Chill Touch with Magus

### ISSUE THREAD

**Issue by Ebonmark** [Truinto/DarkCodex#239]
I looked into it and the rules seem ambigious, but would it be possible to have the touch attacks provided by Chill Touch spell be able to be delivered through weapon attack via Magus Spellstrike, similar to Shocking Grasp? 

Thanks for this mod by the way ~

**Comment by Truinto** [comment]
The attack is stopped before it's delivered. Also mixing it with different touch spells can cause weird attack patterns.
