### ISSUE TITLE
Question: What does the limitless witch hexes do?

### ISSUE THREAD

**Issue by NosVladimir** [Truinto/DarkCodex#240]
I chose that and I have the fortune hex from witch class, but it's still forbidden to cast fortune again on the same character after the effect ends.

**Comment by Truinto** [comment]
Are you sure? I just tried it and it works just fine.

**Comment by NosVladimir** [comment]
> Are you sure? I just tried it and it works just fine.

Thanks for the reply! Then it must be some kind of mod conflict on my side. I'll comment/reopen the issue if I found anything
