### ISSUE TITLE
Feral Combat Training doesn't work with Mythic Unarmed Feats

### ISSUE THREAD

**Issue by BellaRoka** [Truinto/DarkCodex#241]
As stated, Feral Combat Training doesn't work with the mythic unarmed feats, specifically Improved Unarmed Strike (Mythic) and Titan Strike. I tested all other basic feats that had a prereq for base Improved Unarmed Strike and those applied to my Rageshaper's Slam attacks as expected.

**Comment by Truinto** [comment]
Patched Mythic IUS. I can't find Titan Strike. Seems non existent.
