### ISSUE TITLE
Magus spellstrike bug

### ISSUE THREAD

**Issue by qazcdewsx** [Truinto/DarkCodex#243]
When using the magus spell strike  the spell does not get delivered by the weapon attack.
![image](https://user-images.githubusercontent.com/49244539/230653853-9771231e-6b32-4381-9a34-b2c2a89b7f03.png)

I removed all  of my mods except toybox to test this.

**Comment by Truinto** [comment]
I know. This is linked with #239 
It's really hard to understand how the game make touch attacks work.
