### ISSUE TITLE
MadMagic lose effect randomly

### ISSUE THREAD

**Issue by nixgnot** [Truinto/DarkCodex#244]
Not sure what triggered this
but while i have a team using Limitless Raging Song, and all spellcasters pick Mad Magic
Mad Magic will lose its effect randomly (cant cast because of Raging Song) for all spellcasters 
while this happend, i have to deactivate and activate mad magic again to recover its effect.

**Comment by Truinto** [comment]
Apparently the corresponding field isn't serialized into the save file. Other features using that field don't persist long enough for that to matter.
I added the combat start event, which will reapply this feat whenever you get into combat. Should be fixed.

**Comment by Vilacard** [comment]
I know this is marked as fixed, but it seems to still happen with me. I have Mad Magic on all my casters, and limitless raging song on my skald. Sometimes my characters will be unable to cast.
