### ISSUE TITLE
Prodigious Two Weapon Fighting not working

### ISSUE THREAD

**Issue by Endakk** [Truinto/DarkCodex#251]
![Untitled](https://user-images.githubusercontent.com/131301271/233182774-a49b5229-be6b-48df-ac2d-ed7954872ffd.png)
![Untitled1](https://user-images.githubusercontent.com/131301271/233182776-773e3f86-213b-41bd-a921-8373fb8f9b0c.png)
Started up a new save, wanted to go strength based TWF. Get to the chest where you find your equipment post drop into the chasm, and equip two longswords. My attack bonus isn't reading the TWF feature from Prodigious Two Weapon Fighting. Still didn't work after picking up TWF in a later level.

**Comment by Truinto** [comment]
Must be because of a new update. Will check

**Comment by Truinto** [comment]
Idk, looks OK to me. Not sure why this would be different for me.

![pic](https://user-images.githubusercontent.com/47917181/233856977-ef601ed5-6f60-4761-9909-db835d7fa3b8.png)

Btw, super cool character portray.
