### ISSUE TITLE
Flame Blade recieving Odd Size bonus to damage

### ISSUE THREAD

**Issue by knk101** [Truinto/DarkCodex#252]
![image](https://user-images.githubusercontent.com/92350803/233550697-56c9e363-c402-4940-8f5d-1372a352f805.png)

Changing from 1d6 to 3d6 for a size bonus. 

Character is a halfling and is 'small' if that is relevant.

**Comment by knk101** [comment]
Reducing size further by reduce person ( i am now getting +2 size bonus to AC) reducing the flame blade damage to 2d6

**Comment by Truinto** [comment]
Wow. You really get a size bonus when shrinked. Maybe that's an underflow, because the default damage is 0 (plus the overwrite values).
In any case, I set a flag that should prevent the weapon from scaling altogether.
