### ISSUE TITLE
Always a Chance save succeeding where it should fail

### ISSUE THREAD

**Issue by riggs** [Truinto/DarkCodex#255]
47 < 56
<img width="344" alt="CleanShot 2023-05-03 at 03 08 24@2x" src="https://user-images.githubusercontent.com/584232/235864600-1b23ad9f-2627-45e2-9254-8c0e207e0dc1.png">
Aside from Always a Chance, this is what is enabled.
<img width="293" alt="CleanShot 2023-05-03 at 03 21 14@2x" src="https://user-images.githubusercontent.com/584232/235865427-e147b919-98c3-4aae-b6f2-4c119c8b6c26.png">
As far as additional mods, I have ToyBox & Buffs
<img width="900" alt="CleanShot 2023-05-03 at 03 23 16@2x" src="https://user-images.githubusercontent.com/584232/235865865-f0473805-293e-49db-aa04-07b3e1fc88fa.png">

**Comment by Truinto** [comment]
Quote from the main page

Mythic.PatchAlwaysAChance: 'Always A Chance' succeeds on a natural one
and applies to most d20 rolls

Works as intended. You can disable the patch via the ingame menu.

**Comment by Truinto** [comment]
Side note; there is at least one Paizo feature that allows you to turn 1's on damage rolls to max damage instead. So this buff to the otherwise abysmal 'Always A Chance' seems fair in my eyes.
