### ISSUE TITLE
Limitless Spell Synthesis

### ISSUE THREAD

**Issue by rtam2166** [Truinto/DarkCodex#256]
Would love to see limitless spell synthesis for mystic theurges.

**Comment by Truinto** [comment]
That feature does not exist. You probably have this from a mod. Can you tell me which?

**Comment by rtam2166** [comment]
Sorry, I meant that as a suggestion.

If possible, would you add a mystic ability that removes the cost of using spell synthesis?

**Comment by Truinto** [comment]
I cannot find "Spell Synthesis". Do you want to suggest "Spell Synthesis" or "Limitless Spell Synthesis"?
Because it seems weird to ask for a limitless feature for something that does not exist (yet). Maybe I am completely wrong, but again I did not find it.

**Comment by rtam2166** [comment]
Sorry, I just checked and you're original assumption is correct. The feature "Spell Synthesis" was added to the Mystic Theurge in a mod called Mystical Mayhem ([https://github.com/kreaddy/MysticalMayhem](url))

I withdraw my request. Thanks for your time
