### ISSUE TITLE
Cursing Gaze,Shaman can‘t chant as a move action

### ISSUE THREAD

**Issue by UNGONN** [Truinto/DarkCodex#258]
Under turn-based mode.
Before the Shaman get the mythic ability "Cursing Gaze",she can use the ability "Chant" as a move action.
After the Shaman get the mythic ability "Cursing Gaze", she can't use the ability "Chant" as a move action.She has to chant as a swift action or a standard action.

I dont't know how to post a screenshot,sorry.

**Comment by UNGONN** [comment]
Maybe Witch's hex "cackle" were influce by "Cursing Gaze" too.

**Comment by Truinto** [comment]
This is fixed by Patch: Fix Quicken Metamagic. Did you disable this patch?

**Comment by UNGONN** [comment]
Now，I can use 1、Evil Eye or any swift action 2、cackle (not passive) 3、Evil Eye one by one in sequence，with "Cursing Gaze".
I can use 1、one swift action 2、Evil Eye 3、cackle (not passive)   in sequence，without "Cursing Gaze".

But I can't use 1、Evil Eye or any swift action 2、Evil Eye 3、cackle (not passive)  one by one in sequence，with "Cursing Gaze".

**Comment by Truinto** [comment]
That's a pretty bad explaination. A better description would be "cackle
starts as a swift action and becomes a move action, after any swift
action is used, then comes a standard action, if any standard action is
used".

I can see that I chose a bad requirement for my patch and will fix it.
