### ISSUE TITLE
Metakinesis - Selective does not work with the Detonation infusion

### ISSUE THREAD

**Issue by RobMatteson** [Truinto/DarkCodex#26]
Unlike other AOE infusions, Detonation still damages party members when using Metakinesis - Selective

**Comment by Truinto** [comment]
I checked the blueprints and it should have worked. Guess I need to check myself.

**Comment by Truinto** [comment]
Forgot about it. Just checked, feature works as intended, detonation deals no damage while selective metamagic is used.
