### ISSUE TITLE
"Feral Combat Training" feat grants iterative attacks to primary natural weapons, including offhand claw.

### ISSUE THREAD

**Issue by HIMP-Dahak** [Truinto/DarkCodex#263]
As in title. I removed extra abilities like Flurry, Dragon Style, etc from my character, and just having Feral Combat Training was still giving me iteratives, so it's not just from one of those special abilities. There could be an edge case with some other mod, but FCT is definitely what enables the weirdness.
<img width="484" alt="image" src="https://github.com/Truinto/DarkCodex/assets/123663624/34531fe2-06e6-4c01-9bd4-10eb19f88a65">

**Comment by Grimword** [comment]
I dealt with this a while ago with the mod author. It has to do with the engine. It either gives iterative, or doesn't work at all.

**Comment by HIMP-Dahak** [comment]
Drat. That's unpleasant to find out :(

**Comment by YLMstring** [comment]
If I were him, I would just make natural attacks with bab penalties auto miss, ez!
