### ISSUE TITLE
Bug:Toggled/Passive Cackle/Chant acting inconsistencies + Limitless Hex not working on some hexes

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#264]
Often, despite having the toggle version of chant/cackle on, no duration is added to the listed hexes, or they may get their duration increased only some of the time, usually once, but often never or missing 'chunks' of time(i.e if i manually spam click on cackle/chant to get a nice chunk of spare time i can observe that sometimes the 6 second mark passes with no addition, but then on the next 6 second mark it may add time, its very inconsistent)
![image](https://github.com/Truinto/DarkCodex/assets/35548194/c0268510-0535-4a2b-ae65-ab468c7a6c76)
(note the lack of fortune on the buff bar despite it being used, as denoted by the crossed out icon, more on that below)
![image](https://github.com/Truinto/DarkCodex/assets/35548194/abcb7059-9f38-41d2-b87d-e7f69e7ad2f6)
(note that passive chant is toggled on is on)

also like another user has reported i've had issues regarding shaman chanting causing issues when cursing gaze mythic ability is obtained with regards to only working as either a swift or standard action, never as a move action

also it seems some hexes arent getting their once-a-day limit removed by limitless hexes mythic ability, notably Fortune

![image](https://github.com/Truinto/DarkCodex/assets/35548194/d439813b-c82b-4fee-bb4a-526799031717)
![image](https://github.com/Truinto/DarkCodex/assets/35548194/859525f7-a617-4dba-92d5-9ab963900f5b)

**Comment by Truinto** [comment]
I just use the area effect trigger. If this does not trigger, then that's a base game bug. I did not find this happening. It could be location based issue. Or of the game runs longer. In any case, I switched to a buff based trigger. If you still get this bug, I won't be able to fix it.

I found that my previous fix did not consider all possible orders. I changed the condition, which will work now in any order as expected.

I tried limitless hex with fortune on myself and it works perfectly. Cannot reproduce.
