### ISSUE TITLE
Two-weapon rend

### ISSUE THREAD

**Issue by starlight332** [Truinto/DarkCodex#265]
Hello! Is it possible to implement this feat into the game?
https://www.d20pfsrd.com/feats/combat-feats/two-weapon-rend-combat

You've implemented Prodigious TWF and that feat complements STR based TWF playstyle for those, who don't want to go into power attack.

**Comment by Truinto** [comment]
This is quite easy. Rend already exists. There are a couple demons that have this, as well as the bear companion.

**Comment by starlight332** [comment]
Well, it works, but it does trigger more than once so imo the rend that is in the game doesn't have the once-per-round-per-target limit. Thank you very much!
