### ISSUE TITLE
mythic ability: Hexes ignore their cooldown

### ISSUE THREAD

**Issue by skypatel7** [Truinto/DarkCodex#267]
My Understanding is that this ability remove hex limitation of 24 hour cool down e.g. Fortune hex

However it is not working like that. Could you please let me know it's intended use?

![image](https://github.com/Truinto/DarkCodex/assets/3908766/09a0d1bd-263d-450b-ba2c-b5bd38e49645)

**Comment by Truinto** [comment]
That's exactly what it does. And I have already checked that it works. Perhaps there are special conditions for you. Try saving and restarting. Try sleeping a day.

**Comment by Truinto** [comment]
Also, do you have other mods that could undo my changes to hexes?

**Comment by skypatel7** [comment]
I think top tweaks core or top tweaks base is messing with it.

I have following mods.

![image](https://github.com/Truinto/DarkCodex/assets/3908766/1a316509-53f0-4a87-b51d-009273a5fbed)

**Comment by skypatel7** [comment]
I tried changing the load order using info file.

{
    "Id": "DarkCodex",
    "DisplayName": "DarkCodex",
    "Author": "Truinto",
    "Version": "1.5.36",
    "ManagerVersion": "0.23.0",
    "Requirements": [],
    "LoadAfter": [ "TabletopTweaks-Base" ],
    "AssemblyName": "DarkCodex.dll",
    "HomePage": "https://github.com/Truinto/DarkCodex/releases",
    "Repository": "https://raw.githubusercontent.com/Truinto/DarkCodex/master/DarkCodex/Settings/Repository.json",
    "EntryMethod": "Shared.Main.Load"
}

But still no luck.

**Comment by ifarmpandas** [comment]
TTT-Base replaces the `AbilityTargetHasFact` component for hexes [here](https://github.com/Vek17/TabletopTweaks-Base/blob/29330364e5de4cf1d4e9ced3d907e92c5bfdf206/TabletopTweaks-Base/NewContent/Feats/AccursedHex.cs#L85C49-L85C49) so DarkCodex code to do the same doesn't work anymore.

**Comment by Truinto** [comment]
Oh. Thanks a lot. I did not spot this.
