### ISSUE TITLE
Master Shapeshifter Bonuses are Doubled

### ISSUE THREAD

**Issue by gdsdougherty** [Truinto/DarkCodex#269]
I don't think this was present prior to installing this mod.  Let me know if you want the game log, it seems pretty large / may not be related to this bug.
![image](https://github.com/Truinto/DarkCodex/assets/9388859/8ab4c5e5-6904-4861-a824-d4277767f090)

**Comment by Truinto** [comment]
I think this was changed by Owlcat. I made it so the buffs don't stack. So if there are spells that don't grant it (but should) then this fix will keep working. Let me know, if you find anything.
