### ISSUE TITLE
Improved hunter´s bond absent from feat selection

### ISSUE THREAD

**Issue by veidral** [Truinto/DarkCodex#27]
As in title, can´t find improved hunter´s bond in the feat selection interface.

**Comment by Truinto** [comment]
Do you use an archetype? Requirements are ranger 9 and hunter's bond.

**Comment by veidral** [comment]
It´s Arueshalae, so it´s for an archetype, but the thing is, it doens´t even appear among the grayed out feats.

**Comment by Truinto** [comment]
No I meant a non-ranger archetype that grants hunter's bond, if there is one. Guess I have to take a look. I will assume you didn't turn that patch off in the settings.

**Comment by Truinto** [comment]
So my save still has the feat from when I picked it a while back. But I cannot find it when leveling up a new character. Do you also have tabletop-tweaks?

**Comment by veidral** [comment]
I also have tabletop tweaks, yeah.

**Comment by Truinto** [comment]
I made an error. I only added it to combat feats selection, not the regular ones. Wups. Will fix.

**Comment by Truinto** [comment]
Let me know if you find any bugs with the new version.
