### ISSUE TITLE
Bug: Boundless Injury

### ISSUE THREAD

**Issue by GorskaAzdaja** [Truinto/DarkCodex#273]
Boundless Injury does not remove Caster Level limitations of Inflict spells like Boundless Healing does for Cure Wounds, it only converts Inflict to a ray attack.

![image](https://github.com/Truinto/DarkCodex/assets/70537844/81b5e7d0-3bae-470c-9fb9-f6043cd5c047)

![image](https://github.com/Truinto/DarkCodex/assets/70537844/493d8261-7010-4d27-9644-e92b74dd0ed8)

![image](https://github.com/Truinto/DarkCodex/assets/70537844/90802661-35ad-4e18-8d5d-87096d3e7367)

**Comment by Truinto** [comment]
I added only the touch variants to the caster level unlock. Ray attacks wouldn't get the benefit. Fixing in 1.6.1

**Comment by GorskaAzdaja** [comment]
Sweet, my cleric build idea lives! Thanks. If it's too much of a hassle for you, I can make a PR, but not sure what your policy is on that.

**Comment by Truinto** [comment]
I am fine with it. But I already implied that it's done.
