### ISSUE TITLE
Swift Hex Mythic Ability + Cackle

### ISSUE THREAD

**Issue by Vulmar** [Truinto/DarkCodex#275]
After taking the swift action hex mythic ability, hex can be used as a swift and standard action, but not as a move action. This messes up the auto-cackle feature from another mod and it's standard use cases.

**Comment by Truinto** [comment]
Impossible. I already fixed this issue. You probably disabled the fix for quickened metamagic. Swift Hex, like many other similiar feats, just set a metamagic flag and the engine does the heavy lifting.
