### ISSUE TITLE
Can't add abilities to the action bar

### ISSUE THREAD

**Issue by HeruLupercal** [Truinto/DarkCodex#279]
- screenshots
https://imgur.com/5sjWtjd
Please take note of how the "Coup de grace" icon is "hanging" to the left of the ability list, while the cursor is hovering over the same ability in the ability list. The information pop-up and the highlight of the ability confirm the cursor is hovering over the ability.

Here's a gif of the issue (sorry about the watermark and quality I'm a noob at this)
https://imgur.com/a/1LC9ocu

- combat log
N/A

- game log here: "%appdata%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous"
[GameLog.txt](https://github.com/Truinto/DarkCodex/files/13439111/GameLog.txt)

Description:
When using DarkCodex new abilities/spells/items cannot be added to the action bar.

I first click and drag an icon of an ability to the action bar, then release while hovering over the desired slot. However, the game doesn't seem to register the "release" part. The icon of that ability will hover in whatever place the mouse cursor was when the button was released and will "hang" there until I click and drag a new ability or click and drag in the action bar. 
If I click and drag in the action bar, the mouse will again grab the "hanging" icon.
Due to this issue it isn't possible to use the action bars, either the horizontal or the vertical ones. The issue isn't present when the mod isn't installed, this is how I got a few abilities already assigned in first screenshot. 
The gif is showing the issue on a new game.
Both the screenshot and the gif were taken with only the DarkCodex mod installed and none of its options selected.

**Comment by Truinto** [comment]
There was a large update, which broke multiple patches/features. That will take some time to fix.

**Comment by MrGraunke** [comment]
> There was a large update, which broke multiple patches/features. That will take some time to fix.

Waiting eagerly for your update, your mod is one of the best out there!

**Comment by Truinto** [comment]
Disabling mods usually renders the save unusable. You need to wait.

**Comment by Truinto** [comment]
I pushed an update fixing the biggest issues. I suspect there is more to do.

**Comment by HeruLupercal** [comment]
Thank you @Truinto!
The issue was resolved in the latest version of DarkCodex.
