### ISSUE TITLE
Infinite Spirit Weapon Uses and Fighter's Advanced Weapon Training (Warrior Spirit)

### ISSUE THREAD

**Issue by RobMatteson** [Truinto/DarkCodex#28]
Infinite Spirit Weapon Uses removes the limit on Advanced Weapon Training (Warrior Spirit) the same way it does for the Shaman's Spirit Weapon, but the bonuses do not work when toggled on.

**Comment by Truinto** [comment]
What bonuses? I am not familiar with the feature. And it works when used without infinite resources? That's super weird.

**Comment by Truinto** [comment]
I spend some time investigating. But in the end it worked as intended. Maybe you can check again. If you are convinced it's the limitless fault, you can use Toybox to grant/remove LimitlessShamanWeapon at will, comparing the effect.
![pic](https://user-images.githubusercontent.com/47917181/153903781-a4da7e4a-1632-43fb-abd0-2d4f673e6b9d.png)
