### ISSUE TITLE
power attack icon doubled with time limit on one instance

### ISSUE THREAD

**Issue by gdsdougherty** [Truinto/DarkCodex#280]
![image](https://github.com/Truinto/DarkCodex/assets/9388859/0725a994-3410-4a4a-9316-6069a6c05e6e)
This might be related to owlcat's change so feel free to dismiss if that's the case / unrelated to your code, but the icon is doubled after making an attack and one has a time limit of 6s / 1 round.
Looking a bit further into it, I can see that when this is present the damage / attack preview also show the effects of power attack which is not true prior to making an attack that round post the 2.2.0 update, which also makes me suspect it's owlcat's change.  Just reporting it here so you have the opportunity to review in case that's not the case.

**Comment by Truinto** [comment]
There are a ton of buffs which are just hidden at all times. I suspect this buff isn't new, but the flag for visibility was changed. Hiding it again would be easy for me.

**Comment by gdsdougherty** [comment]
Looks like it's also the case for deadly aim, and I'd assume piranha strike.
![image](https://github.com/Truinto/DarkCodex/assets/9388859/cf7daebb-3377-40e4-8df2-0aa83c9e6056)

**Comment by Truinto** [comment]
According to bubble's blueprint dump, these buffs should be hidden by default. I will set them to hidden, but that may have no effect.
