### ISSUE TITLE
Hotbar Abilities Cannot be Moved and 'Persist'

### ISSUE THREAD

**Issue by Envibel** [Truinto/DarkCodex#283]
When dragging an ability on the hotbar to another slot or outside the hotbar to remove it, the icon will instead just be left floating wherever you let go of the mouse and the ability will remain in the same slot. When I uninstalled Dark Codex the problem stopped occuring.

![image](https://github.com/Truinto/DarkCodex/assets/113065492/f950ac81-1b1f-44ca-9cf7-16aa11727aad)

**Comment by Truinto** [comment]
Mh yeah possible. Probably a soft crash with the handler for spellpouch. You did update DarkCodex, right? I guess there was another patch after I tried it.

**Comment by Envibel** [comment]
Yea, it is updated. Modfinder cannot find any updates for it and my version number matches the latest release version number, 1.6.0

**Comment by Truinto** [comment]
No, I checked again and it's working fine. Either this happens only in specific circumstances or you have another mod that has CodexLib embedded (which is exactly what I ask people not to do).
For the latter, remove these mods from the Mods/ folder. It's not enough to disable them.

**Comment by Truinto** [comment]
Expanded Elements will have the same issue. Updating CodexLib.dll might fix it.
