### ISSUE TITLE
Plague of Abaddon doesn't work with Cursing Gaze

### ISSUE THREAD

**Issue by gazorpaz** [Truinto/DarkCodex#284]
Plague of Abaddon from the new shaman archetype stays standart action even with cursing gaze mythic ability. Bug or by design?

**Comment by gazorpaz** [comment]
Still unable to use the plague ability as a swift action.

Carrier of Disease was present in the Cursing Gaze tooltip.

**Comment by Truinto** [comment]
Oh, that's a singular ability and the selection are just buffs to that. Then my search function won't work. Will change it.
