### ISSUE TITLE
Wolverine Form no longer counts as prerequisite for limitless rage

### ISSUE THREAD

**Issue by gdsdougherty** [Truinto/DarkCodex#288]
Looks like owlcat adding rampage as a qualification for limitless rage might have broken your implementation of the wolverine form qualification for limitless rage (I'm seeing that on a character with wolverine form).  Thank you for implementing that previously by the way.
![image](https://github.com/Truinto/DarkCodex/assets/9388859/17a1787e-d668-4577-9078-07a524407b99)
As a side note, since it's implemented by owlcat now, it might make some sense to remove Rampage as a potential qualification at least from the mod, though I'd be worried about if that could affect existing save files.

**Comment by Truinto** [comment]
The prerequisite I picked was at level 8 and flagged as 'hide-in-ui'. I picked a different one I think it correct.
