### ISSUE TITLE
issue for Flame Blade.

### ISSUE THREAD

**Issue by nixgnot** [Truinto/DarkCodex#292]
while you wielding Flame Blade,  it will show the action bar of PREVIOUS character in your turn (in turn combat).
means you cant choose your own ability.
it will restore after you switch to realtime then switch back immediately.

and if you are the first active character, your action bar will be shown in next guy's turn

Same for trident.
![1](https://github.com/Truinto/DarkCodex/assets/20860979/24e3be93-2158-4f40-8500-ef5eafe755a1)

and casting Flame Blade while you wielding other weapon will made the game stuck  before or after you use Flame Blade to attack.(in turn combat)

**Comment by Truinto** [comment]
[Player.log](https://github.com/Truinto/DarkCodex/files/15052841/Player.log)
