### ISSUE TITLE
Metamagic Master & Magic Lineage backgrounds not working for certain spells?

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#293]
expected behavior: spell selected during character creation would make said spell have it's level raised by fewer levels when applying metamagic feats

encountered behavior: some spells posses extra "copies" within it's selector(possibly NPC versions?) which seem to not work with the backgrounds, these copies dont seem to be present in the selector for Spell Perfection

**Comment by Truinto** [comment]
Connected to #296. Should work now.
