### ISSUE TITLE
Can't Find Demon Lord Ability

### ISSUE THREAD

**Issue by BlackHatM4stah** [Truinto/DarkCodex#310]
I'm not sure where the Demon Lord ability is supposed to show up, but I can't seem to find it.

**Comment by Truinto** [comment]
These are mostly passive immunities. Identical to what the other demon lords get. Teleport is a 4th level spell you get normally and with this it won't get consumed (thus at will).

I did think about implementing the once per year free resurrection, but that's low priority.
