### ISSUE TITLE
Automatic bonus progression inspired mod

### ISSUE THREAD

**Issue by GianPel90** [Truinto/DarkCodex#32]
Hi! It's me again! I'm still thankful for the implementation of the Axe and Impact enhancemente BTW!

This time I was thinking about the hassle of equipping all the party with the "standard issue magic items". I find a Ring of Protection +4, so I have to change my Ring of protection +3 for my MC, then pass the +3 to a character with a +2, etc.
It is also a fact that it limits the use of situational or stange items which require slots.

So I thought: why not use something like the APB? For reference:
https://www.d20pfsrd.com/gamemastering/other-rules/unchained-rules/automatic-bonus-progression/

Of course implementing this in the leveling process would be pretty difficult (I imagine) and long work, so I came up with a work-around: using an item in the 'usable slots', likely in the protagonist, which will provide the bonus for the whole party (I remember seeing pets or other items affecting the whole party).
This way one could buy from the main vendors (in defender's Heart, Drezen etc) the ABP for the equivalent of the slew of magical items it substitutes.
This has the additional benefit of not having to switch so many items when changing party members!

I will soon post a table with some ideas, let me know you think about it and if you think it's worth for you to make it or it doesn't interest you ^^

**Comment by GianPel90** [comment]
The ideal would be the possibility to buy and sell at the same value, so when one wants to 'upgrade' the item there is no loss of gold. In alternative one could take out the 3/4 of the previous Tier from the successive ones.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/phoen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/phoen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Defense   bonus item | Resistance | Deflection | Natural | Worth
-- | -- | -- | -- | --
Tier 1 | 1 | 1 | 1 | 30000
Tier 2 | 2 | 2 | 2 | 120000
Tier 3 | 3 | 3 | 3 | 270000
Tier 4 | 4 | 4 | 4 | 480000
Tier 5 | 5 | 5 | 5 | 750000



</body>

</html>


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/phoen/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/phoen/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Ability   bonus item | Physical | Mental | Worth
-- | -- | -- | --
Tier 1 | +2/+2/+2 | +2/+2/+2 | 192000
Tier 2 | +4/+4/+4 | +4/+4/+4 | 768000
Tier 3 | +6/+6/+6 | +6/+6/+6 | 1728000



</body>

</html>

As you can see the bonus is general because it has to benefit every kind of character (martial and casters alike). It's fairly expensive, but I'm in the middle of chapter 3 and have around 500.000 gp without anything to do with it (crusade is already easy enough without inflating the resources there, and I prefer to consider it a minigame inside the game).
Also selling every Ring of Protection, Amulet of Natural Armor, etc should cover a part of the expenses.

Any feedback about this?

**Comment by Truinto** [comment]
How I would make this: Remove all basic enchantments from equipment. Add activatables to every character that allows them to apply the listed bonuses.

Unfortunately the logic is pretty difficult. It's a lot of work. It's a cool idea, tho. I won't be able to finish this anytime soon.

**Comment by Truinto** [comment]
Yeah, that's too much work. There is so much other exciting stuff, I don't think I will ever come doing this.
