### ISSUE TITLE
Multi-cost abilities not being affected by infinite use Mythic Abilities

### ISSUE THREAD

**Issue by phudspeth** [Truinto/DarkCodex#34]
Hi there! Really love the mod and the cool additions you've made.

I'm just having a bit of an issue with mark of justice, and the battle singer archetype and still having use costs associated with them. Per the limitless smite/limitless ragesong abilities they should be similarly infinite use but they're still showing as having a specific amount of uses. I think it's specifically due to the 2 uses instead of 1 use like normal abilities. E.g. Smite evil is unlimited use, ragesong is unlimited use, first verse is unlimited use (first verse uses only 1 round of performance), but mark of justice, second verse, and third verse all have specific amounts of uses required.

**Comment by Truinto** [comment]
Added option in menu to reduce cost to 0. Needs restart to switch setting. Please let me know, if this works. The logic is simply, I didn't bother to play test.

**Comment by phudspeth** [comment]
No dice, still costs uses when you activate the abilities. I did a homebrew patch with it by altering the m_costsresources boolean to false, granted I know nothing about mods so it was a universal fix.

**Comment by phudspeth** [comment]
Disregard, seems to be working now! Might have just been loading improperly, not sure.

**Comment by Truinto** [comment]
> Needs restart to switch setting.

You probably didn't notice. It is generally possible to have all features enable/disable immediately. But it triples the work and potential bugs. So usually any settings changes require a restart (*unless noted otherwise).
