### ISSUE TITLE
[for-debug] Limitless Mythic Feats removing multiple weapon animations

### ISSUE THREAD

**Issue by sylothix** [Truinto/DarkCodex#38]
I'm unsure whether reporting issues met in the for-debug version is useful but I'm dropping this here anyway. 

Experienced an issue after using the debug mode that some of my character no longer had weapon animations, bows, crossbows, axes,  spears. and longswords were most the most noticable. Though oddly enough some weapons like the Gnome Hooked Hammer and Kinetic Blade still appeared to function normally, wasn't able to test all weapons however. 

Managed to isolate the issue to whenever any one of the Limitless Mythic Feats were activated. Having them all unticked had weapon animations function normally.

**Comment by sylothix** [comment]
Update: DarkCodex3 seems to have solved the problem, thank you!

As a side note since I'm unsure where to ask this, can I manually add stuff into the DefGroups.json to make my own foldable ability groups? Or can I not do that in the json file?

**Comment by Truinto** [comment]
Yeah that file wasn't meant for public. I didn't think that through :D
Reason for that bug was a mistaking in my blueprint loader which didn't populate the visual parameters. These aren't used by double weapons and some other exceptions.

Please only play with files published in the release tab. Anything else is even more likely to corrupt your game/save.

**Comment by sylothix** [comment]
I initially found the for-debug version from a link in the wotr discord and got really hooked at all the new foldable categories and find it difficult to go back to the limited options the live version provides. 

On another note, I did manage to add a few stuff into DefGroups.json and managed to get all of the Judgments in there too. Down below if needed, I just found categorizing stuff fun.
  {
    "Title": "Judgment",
    "Description": "Judgment",
	"Icon": "ddffa896d4605a44f95baa6d0d350828",
    "Guids": [	  
	  "4ebaf39efb8ffb64baf92784808dc49c",	// Destruction
	  "00b6d36e31548dc4ab0ac9d15e64a980", 	// Healing
	  "ddffa896d4605a44f95baa6d0d350828", 	// Justice
	  "487af80cdfbaad74b8c2fd644c538233", 	// Piercing
	  "1bb08308c9f6a5e4697887cd438b7221", 	// Protection
	  "15d3b21354c105b498a0b1b293280ded", 	// Purity
	  "ad61fc9dec7822b45891c78c9da5d5da", 	// Resistance
	  "bfec9cee57e7a7d47a8641c5c9d43c41", 	// Resiliency - Magic
	  "d7e61eb9f0cec5e49bd1b0c428fa98e4", 	// Smiting - Level 1
	  "72fe16312b4479145afc6cc6c87cd08f", 	// Smiting - Level 6
	  "1f7e326d3a88fd84985a60e416388c27", 	// Resiliency - Evil
	  "3bb25de520e78744ea3ac406b918ab3e", 	// Resiliency - Lawful
	  "d47ecfecae485ac41b54fe4e8027797c", 	// Resiliency - Good
	  "1452fb3e0e3e2f6488bee09050097b6f", 	// Resiliency - Chaotic
	  "2c448ab4135c7c741b6f0f223901f9fa", 	// Smiting - Level 10
	]
  }

**Comment by Truinto** [comment]
Yeah, this feature is really amazing. It cost me a lot of work, but was worth it. I added an option to reload during gameplay. The groups will update when you open the ability main tab.
I was also thinking about making this interactive. I should be able to inject code into the logic that usually swaps abilities (e.g. the target already has an action slot).
