### ISSUE TITLE
1.2.1 bugs out Minagho in the Drezen citadel

### ISSUE THREAD

**Issue by EnderWiggin** [Truinto/DarkCodex#39]
Minagho at the end of Drezen speaks Latin (Lorem ipsum dolor...) with broken dialog box. I've looked into GameLogFull.txt and found bunch of exceptions on unit Minagho_DrezenCitadel_Boss:

> [121.4630 - Default]: Exception in UnitActivatableAbilitiesController on unit Unit[Minagho_DrezenCitadel_Boss]#856FF
> [121.4720 - Default]: Exception in UnitCommandController on unit Unit[Minagho_DrezenCitadel_Boss]#856FF
> [121.5100 - Default]: Exception in UnitProneController on unit Unit[Minagho_DrezenCitadel_Boss]#856FF
> [121.5110 - Default]: Exception in UnitAnimationController on unit Unit[Minagho_DrezenCitadel_Boss]#856FF

Started searching mod repos and found that this mod added file with `UnitActivatableAbilitiesController` couple days ago, and decided to revert to 1.2.0. At first it didn't work - I've loaded a save right behind a door to her and Staunton and still got broken dialog. But after loading save made before entering citadel (right before getting mythic 3) she started talking properly.

**Comment by Truinto** [comment]
First off, thanks for investigating and telling me about it.

>this mod added file with UnitActivatableAbilitiesController
No, it doesn't. But I do have AbilityExecutionProcess.Tick which is related to it. Tho, that patch wasn't changed in a way that could have such an effect.

Can you proved the save just before that bug happens? I also need a list of mods you run.

**Comment by EnderWiggin** [comment]
used mods (don't knoiw of a better way to share this):
 ![image](https://user-images.githubusercontent.com/570237/160297481-c4510c67-694d-4bd0-811d-4ada64a3ed2f.png) 
Quick cast is actually disabled from in-game menu. Also don't know if you'll need any settings from any of those mods.

[Manual_155_tmp.zip](https://github.com/Truinto/DarkCodex/files/8358329/Manual_155_tmp.zip) save right before the door with Staunton and Minagho, dialog should be broken on both 1.2.1 and 1.2.0

[Manual_153_Big_Mythic_Choice.zip](https://github.com/Truinto/DarkCodex/files/8358332/Manual_153_Big_Mythic_Choice.zip) save right before accepting 3rd mythic level, it is a short walk from there to the citadel, dialog works fine if citadel is reached on 1.2.0, broken if reached on 1.2.1

**Comment by Truinto** [comment]
I reverted one change, which probably fixes this. Will look into it at a later time. Just download 1.2.1 again.

**Comment by Truinto** [comment]
Tried this with the upcoming version and everything worked fine.
