### ISSUE TITLE
Request/Idea: Pseudo Kinetic Whip?

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#4]
how hard to implement would it be to make the kinetic blade specifically for kinetic knights act as reach weapons, be eligible for Attacks of Opportunity and the special qualities from PnP(bonus to disarm, trip and performance)?

obviously changing visuals is out of the question but just the passive effects seem like they could be doable if creating a separate kinetic blade for knights is possible

**Comment by Truinto** [comment]
Already working on whip infusion. I have trouble with increasing the burn cost, which should have been the easy part.

**Comment by Truinto** [comment]
Made whip infusion. Sometimes the reach increase doesn't seem to work. I noticed the same with enlarged creatures. I am not sure, if this is a general bug or my issue. Let me know, if you figure anything out.
