### ISSUE TITLE
Limitless Arcane Pool isn't working for Eldritch Scion.

### ISSUE THREAD

**Issue by Adsam112** [Truinto/DarkCodex#40]
When using the Eldritch Scion archetype for magus the limitless arcane pool doesn't seem to work
![Screenshot (18)](https://user-images.githubusercontent.com/49521120/160414988-3c7e4534-e6cf-4949-a906-b24fef424ec1.png)
![Screenshot (17)](https://user-images.githubusercontent.com/49521120/160415044-6a7ca99a-91fc-4640-a1dc-e2908bb2cb7d.png)
As you can see I have both Mythic abilities but the eldritch pool is still limited
![Screenshot (19)](https://user-images.githubusercontent.com/49521120/160415207-f3b0c6cf-3925-48c6-bfa1-12ece6c46290.png)
It still runs out after use.

I've tried with the option to make Limitless cost 0 both on and off with no change. It seems to be just the eldritch scion since regular magus works as do all other limitless abilities such as warpriest, rage, ki ect.

**Comment by Truinto** [comment]
Yeah, it has a separate resource pool, so I overlooked it. Will be fixed with the next release.

**Comment by Truinto** [comment]
I included this in 1.2.2. Didn't playtest tho. Let me know. Btw, 3 people reported issues since 1.2.1, so use with caution and keep a save.

**Comment by Adsam112** [comment]
It seems to be working again so i can say it's just about fixed. Also do you still plane to add chain infusion to thunderstorm blast?
