### ISSUE TITLE
1.2.1 Causes my saves to be unloadable and occasionally stops the game loading at all.

### ISSUE THREAD

**Issue by Woffingshire** [Truinto/DarkCodex#41]
Since updating to 1.2.1 I have not been able to load any of my saves that used 1.2.0, every time I try it gets to around 6-10% loaded and then sends me back to the menu screen.

I have troubelshooted and confirmed that it is this mod causing it. Reverting back to 1.2.0 fixes all the issues.
On rare occasion the save will get higher than 10%, then the entire game will crash and will continue to crash on boot unless I delete everything in my LocalLow folder for the game. This too I have confirmed is caused by 1.2.1.

**Comment by Truinto** [comment]
Must be the faster blueprint loading function. What other mods do you have installed? Maybe I created incompatibilities.

**Comment by Truinto** [comment]
I reverted one change, which probably fixes this. Will look into it at a later time. Just download 1.2.1 again.

**Comment by Woffingshire** [comment]
The other mods I have installed are Magic Time! Tome of the Firebird and TableTop Tweaks. Well, they're the mods that add content that might conflict with yours anyway.

**Comment by Woffingshire** [comment]
Here is the link to the save and picture. https://we.tl/t-frKapP8vq4
The crossed out ones on my mod list are the ones that are not installed

**Comment by Truinto** [comment]
I will try out the save some other time (tomorrow?). Until then I released 1.2.2. If 1.2.1.1 didn't help, this one probably neither. But worth a shot.

**Comment by Truinto** [comment]
I cannot load your save, regardless of which version I use. It's missing this guid: 3779162082e54a7894c5077f717c9603
This is none of mine, so I am probably missing a dependency mod. I did download all the mods in your screenshot tho...

Please try the follow. Install the latest DarkCodex, open the mod menu, scroll all the way down and enable "debug2". Then load your save. If it's stuck at 100% for more than a minute use ALT+F4 to close the game. Then copy and send me Player.log and GameLogFull.txt located here:
%appdata%\..\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous

If you are done, you can downgrade to 1.2.0 again. Remember to disable debug2 (it destroys traps in your current location, which sometimes causes me crashes).

**Comment by Truinto** [comment]
I think this has been resolved.
