### ISSUE TITLE
Magus enduring blade + greater enduring spells. 

### ISSUE THREAD

**Issue by tripwirez** [Truinto/DarkCodex#42]
When using enduring blade + greater enduring spells to buff weapons using arcane weapon enhancement, buff shows itself as lasting for 24 hours, but falls off within a minute or so as if no enduring blade was even being applied.

**Comment by Truinto** [comment]
Honest question, how is this related to my mod?

**Comment by tripwirez** [comment]
You've got a patch that allows enduring spells to apply to spells from any source - which, unless I'm mistaken is what is allowing greater enduring spells to be applied to the magus ability arcane weapon enhancement when using enduring blade to extend the buff duration to 5 minutes.

**Comment by Truinto** [comment]
Before 1.2 Enduring Spell would work on any spell-like ability. Like racial spells or spells from scrolls. This was changed. I changed it back.
Isn't the minimum duration needed 10 minutes, not 5?
Buffs are usually added as children. Meaning if the feature granting the buff is removed, the buff ends immediately. Is that what's happening?

**Comment by Truinto** [comment]
OK, got it now. The buff has no function other than being visual. The effect is separate and not something caught by Enduring Spell.

**Comment by tripwirez** [comment]
Ah, yeah. That seems to be it. Is that something you can fix? If you could, great! That's absolutely what I want. But if not, would it be possible to exclude arcane weapon enhancement from the list of spell-like abilities affected by greater enduring spells when running the patch so I at least don't get the visual bug?

**Comment by Truinto** [comment]
I included this in 1.2.2. Didn't playtest tho. Let me know. Btw, 3 people reported issues since 1.2.1, so use with caution and keep a save.

**Comment by tripwirez** [comment]
Right on. I'll give it a shot and report back if I run into anything.

**Comment by tripwirez** [comment]
So, after a quick preliminary test: the buff now seems to last the full 24 hours, so long as you don't do anything like rest or change areas. If you rest or change areas, it drops off just like it was before, leaving the buff icon active for the remainder of the 24 hours, but not giving you any of the benefits. 
Still, seems like a step in the right direction.

**Comment by tripwirez** [comment]
Okay, so, I don't know what's going on here, exactly. I thought it might just be a problem with arcane weapon enhancement, but I actually get the same problem using magic weapon, and greater magic weapon spells. If you extend any of those to 24 hours, loading or even SAVING a game, resting, or changing areas all immediately suspend the buffs effect while leaving the buff icon active. Otherwise, the buff will act normally and stick around the full 24 hours.

**Comment by tripwirez** [comment]
Yeah, I messed around with this a bit, trying a non-modded game with a level 20 inevitable excess character, and got the same drop off from the weapon enhancements. So it looks like a base game thing. Does the presave function trigger itself intermittently or something? Because I would sometimes lose the enhancement just at random, regardless of whether or not I saved or changed areas.

**Comment by Truinto** [comment]
I changed the arcane weapon buff to be replaced instead of stacking.

**Comment by tripwirez** [comment]
Ah, right on. That's at least one nuisance taken care of. Appreciate your work on this!

**Comment by Truinto** [comment]
> SAVING a game, resting, or changing areas all immediately suspend the buffs effect

So I am testing this right now and the effect seems to persist. What weapon do you enchant? Because if you cast this on temporary weapons it will certainly fall off when you remove the weapon. Same goes for weapons from activatables like the demon's natural weapons.

**Comment by tripwirez** [comment]
Ah, you're right. I've been chanting my unarmed fists. I guess they count as temporary weapons? Well that's unfortunate :/

**Comment by Truinto** [comment]
So I looked at the EmptyHand slots and I can't seem a difference to any other weapon item. But since it doesn't happen with weapon items, I guess that they are different somewhere. I cannot figure it out. Maybe make a bug report to Owlcat (since you checked it happens without mods).
