### ISSUE TITLE
Resourceful Caster + Destructive Dispel + dispel magic bug

### ISSUE THREAD

**Issue by phudspeth** [Truinto/DarkCodex#43]
So when you have destructive dispel and resourceful caster and you cast on a target and they save from all the destructive dispel saves it gives you the spell back per resourceful caster. Probably not the worst bug ever, and I guess debatable if that's not intended but I figure since it's a spell rider instead of the spell itself it might not be what you were going for.

**Comment by Truinto** [comment]
Yeah that is undesirable. Including the dispel action into the logic should be no problem.

**Comment by Truinto** [comment]
Fixed in 1.2.4
