### ISSUE TITLE
Mod Manager doesn't show that this mod has updates

### ISSUE THREAD

**Issue by EnderWiggin** [Truinto/DarkCodex#44]
Probbaly because https://raw.githubusercontent.com/Truinto/DarkCodex/master/DarkCodex/Settings/Repository.json has ID **FumisCodex**, but in info.json ID is **DarkCodex**

**Comment by Truinto** [comment]
Damit :)
You are right.

**Comment by Truinto** [comment]
Updated. Thanks for the info.
