### ISSUE TITLE
One or two more ideas/requests ^^

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#46]
Repost from the discussion section since I read you usually do not consult it !

Hey there, a little request since there already is a collection of varioux fixes and new additions ^^

Would it be possible to add a feat that would allow casting while enraged ?
By RAW it's a metamagic feat with extra bits but I'd rather have a feat for just the casting part...

Perhaps it's not that simple since there are quite a few rage features with barbarian/skald/instinctual warrior etc... (but hey, the latter would be quite something since there is no other (morale?) WIS bonus for casters !)

Completly unrelated : would it be possible to re enable the basic arcanist capstone (Magical supremacy) for either the Phantasmal mage or the Brown fur transmuter.
For one I think it's not quite overpowered since there already is a heavy usage of arcane points for other things, and on top of that it would allow both archetypes with the cumulative rules :p

**Comment by Truinto** [comment]
Will see with rage. The capstone is too specific. I can tell you how to get that with Toybox, but it seems unnecessary to code.

Btw, I got a notification but didn't think to look in discussions :P

Also, the game does not support multiple archetypes at all, even if legal. The complexity would have been significant, so I can totally see why.

**Comment by Mythalar** [comment]
Thanks !

Well I guess I can add features from one archetype to the other (probably simpler to add BFT to Phantasmal).
Just adding powerful charge and other abilities should work I guess)

Multiple archetypes can be used with Toybox actually without any issue so far (it deactivated conflictual archetypes as should be)

**Comment by Truinto** [comment]
Was a bit in rush because of the game update. Would you mind testing "Mad Magic"?

**Comment by Mythalar** [comment]
So I tested the feat with Instictual warrior (so Focused Rage), and could neither cast spell nor use kinetic blasts (since they are spell like).

**Comment by Truinto** [comment]
Works now. I forgot to add a null check.

**Comment by Mythalar** [comment]
So far all good among various tests, thank you very much :)
