### ISSUE TITLE
Spell, Action, and Belt Bars Inaccessible 

### ISSUE THREAD

**Issue by MiHaSt0** [Truinto/DarkCodex#47]
As of the new 1.3,0k, I am unable to access the expanded spell and action bars. Hotkeyed abilities do still show up in combat, although not out of combat. I was able to verify that this does not occur with Dark Codex uninstalled on a new character, Understand that new patches muck things up; just wanted to bring it to attention!

**Comment by Truinto** [comment]
Thanks. I have slow internet and a busy schedule, so I only just downloaded the huge patch. Gonna take some time until I can review the issues.

**Comment by 0utrider** [comment]
Confirming this, too. All the quick bars go away outside of combat, and they are not fully functional in-combat.

Some clarification what happens: [https://imgur.com/a/deeeuAG](https://imgur.com/a/deeeuAG)

Appreciate you and your awesome work, as always

**Comment by Truinto** [comment]
Works again 🎉
