### ISSUE TITLE
Request: Bladed Dash arcane spell?

### ISSUE THREAD

**Issue by Vilacard** [Truinto/DarkCodex#49]
https://www.d20pfsrd.com/magic/all-spells/b/bladed-dash/

Would it be possible to add this to the magus skald and bard spellbooks? In Kingmaker, I think the Call of the Wild mod added it, as well as the Blade Rush kineticist infusion. It seemed to be pretty much exact same as the Blade Rush kineticist infusion, and since your mod has already added that I thought it might be possible to add the spell as well.

Thanks!

**Comment by Truinto** [comment]
Yes

**Comment by Truinto** [comment]
Made progress. Will need to check how to do the attack bonus. Also doing the Greater version of the spell.

**Comment by Truinto** [comment]
Implemented and tested. I didn't check if it shows up in the spell list. Let me know, if it's not working.

**Comment by Vilacard** [comment]
Both Blade Dash and its greater version appear and are selectable by Magus, Bards, and Skalds. There still seem to be other bugs though.

Regarding Blade Dash: 
It doesn't seem to grant the int or cha bonus to hit at all. 
As a magus, it doesn't seem to work with spell combat in that I don't get my normal attacks afterwards.

Regarding Greater Blade Dash: 
-It doesn't seem to do damage at all. It'll still roll to attack any targets, it just doesn't do any damage rolls.
-When it does do the attack roll, I'm pretty sure it's using the bonus int/cha to hit is using its actual full value instead of just the bonus: my magus got an Other bonus of +21 to attack and they had 21 int. A skald in my party got an other bonus of +16, when they had 16 cha.
-It doesn't seem to actually hit party members at all (no attack rolls), but seems to hit friendly npcs(still no actual damage roll though).
-Unlike regular Blade Dash, it does seem to work fine with Magus's Spell Combat, although still no actual damage roll from Greater Blade Dash itself.
-It doesn't seem to work with Reach metamagic at all. Regular Blade Dash does, though.
-Pretty minor, and no clue if this is intended, but it seems to be able to put you over edges. When I was initially testing, I was up on the walls during Drezen in Chapter 2, and it'd put me down below.

**Comment by Truinto** [comment]
It's intentional to not hit allies. Truly friendly NPCs are invulnerable. Neutral NPCs are hit.
I forgot to insert the damage roll for greater. Will fix.
The teleport has standard restrictions. So if you get over ledges, that's true for other teleports as well.
Will check why the stat bonus uses raw values.
About regular version. It's difficult to buff only attacks from the spell with the existing components. I probably rework this.
Did you test the spell combat in turn-based or real time?

**Comment by Truinto** [comment]
Should work now. Thanks for all the feedback.
Btw, Blade Dash will now hit the first possible target, instead of being limited to the exit position.

**Comment by Vilacard** [comment]
All of the things I posted about seem to have been fixed. Thanks! All of my testing has been done in turn based.

Regarding regular Blade Dash:
-The targeting reticle is a long fat line like the one Greater Blade Dash has. At least personally, I prefer it to be just something you target like you would for other single target abilities.
-The tooltip says it'll hit all creatures in a 30 foot line, but it only actually hits the target you select. So no actual functional issue, it's just a tooltip one.
-If I actually click a target, it doesn't seem to do an actual attack. No attack roll or damage roll at all. Despite that, I am still in melee range and I can get my followup attacks with spell combat. If I select near the target, as in melee range, I will get the attack+damage rolls.  Targeted: https://streamable.com/cxime1    and nearby: https://streamable.com/0pb0yi

Regarding Greater Blade Dash:
-Since you said it's intended to not hit allies, this is only a tooltip issue but it says it'll hit all targets in a 30 foot line.
-It also has similar targeting issues that regular also has. https://streamable.com/8m6u8k https://streamable.com/y6bt2f https://streamable.com/7zrrrn

**Comment by Truinto** [comment]
Yeah the targeting might feel wrong, because it will hit only one target. But both abilities use the same component now, which made this much easier to code.
The tooltip... is auto generated based on the type of component. I noticed the tooltip to be inaccurate regarding allies hit, even with base game abilities. So that's a separate bug. Maybe I can fix that.
I see the area is a bit too short. I will extend it by 5 feet or so. Perhaps I check the player's reach, if there is a way for that.

**Comment by Truinto** [comment]
I think I fixed all issues. The only time it fails is if you stand in melee range and point exactly on that target. Fortunately it makes no sense to use it that way.

**Comment by Vilacard** [comment]
The tooltip for Greater was fixed, and the targeting method for regular was changed so that's good. Thanks!

Unfortunately, some of the bugs I posted about still persist. 

For both regular and greater, if I actually click on an enemy with a non reach weapon, I won't get the attack granted by the spell. If I do equip a reach weapon, I do get the attack. If I select my exit point as very close to the target, I do get the hit with a non reach weapon. This can be seen in the targeted video for regular blade dash in my previous post. Even without a reach weapon though, I still do get my follow up attacks from spell combat.

About Greater, in my first video about it it says I can't target the dretch sitting behind the brimorak. This still persists. What did seem to get fixed though was if I placed my exit point very close to the dretch, both the dretch and brimorak got the attack.

Honestly these issues don't really bother me personally after doing testing over the past few days, but it might be confusing for a player who hasn't.

**Comment by Truinto** [comment]
So only reach weapons work. I didn't notice, because the character I tested with was enlarged. Weird that this still happens. I add the actual reach to the line's length. I think that includes the units corpulence. Guess I will increase it by an extra meter.

**Comment by Vilacard** [comment]
Unfortunately the targeting issue still persists in 1.3.4. https://streamable.com/3c7u1h Although I use regular here, the same issue hapens with Greater still.

Some additional weirdness pops up now though. If 2 targets are relatively close together and I set regular blade dash's exit point to near one of them, it'll hit the 2nd target. Even if it'd mean a reach of like 10 feet. https://streamable.com/qwpfjg

The issue  of one target being behind another target being untargetable with Greater still persists as well. Targeting near them works fine, though. https://streamable.com/ewvify

**Comment by Truinto** [comment]
>Even if it'd mean a reach of like 10 feet.

That's the additional reach I added in to hit the main target. Guess the range wasn't the issue. I also just realized that because the projectile is so fast, it will sometimes select targets in order of creation, instead of the closest unit.

I will make an overwrite, so the main target is always preferred.

**Comment by Truinto** [comment]
I didn't think their would be so much fine tuning for single spell. It won't get any better than now. Consider this ticket double closed :D

**Comment by Vilacard** [comment]
As far as I can tell after some quick testing, all the problems I encountered have been fixed.

Thanks for implementing it, and for all the fine tuning!
