### ISSUE TITLE
Perhaps bug fixing this time...? :p

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#50]
First a so very big thank for the creation of ability groups, that allows me to make any gestald builds that I ever wanted but could not quite use since tha ability tab was full so some would be hidden...

So something that bugs me, and was perfectly summerized by [Frijdom in TabletopTweaks](https://github.com/Vek17/TabletopTweaks-Base/issues/407), is the fact that Elemental bloodlines arcanas, or any elemental damage conversions really, do not account for the various feats (Elemental focus) or items that would boost the final element but only the original one.

I think that defeats the purpose of elemental bloodlines and such since, as a fire elemental sorcerer, I would want to focus on fire (Fire focus feat), and use some rings that add fire damages and such, but if I convert lightning bolt to fire none of those work...

Call of the Wilds fixed it for Kingmaker but no mod fixes it right now for WotR.
It all the more confusing that the logic is surely there since Ascended element takes the final element into account (well I guess pure damage issues are separate from spell register things...)

**Comment by Truinto** [comment]
BloodlineElementalFireArcanaBuff (b3e3882ab6829e34983f31e989c00dfc) applies ChangeSpellElementalDamage which changes the spell descriptor right before the damage is dealt.
ElementalFocusFire (13bdf8d542811ac4ca228a53aa108145) applies IncreaseSpellDescriptorDC when the ability parameters are determined, which is way earlier.

So I can see why the change in element does not affect the DC. Calculating the DC any later would not work, since the saving throw happens before the damage. Changing the element earlier... needs to be seen.

**Comment by Mythalar** [comment]
Ok I see now the logic.

I don't know how it has been fixed in CotW back then, but it's really inconsistent now and, I think, counter intuitive since the spell descriptor should be the first thing to be altered -_-

**Comment by Truinto** [comment]
It's a nightmare to fix this. I think I got it. Would you mind testing it out?

**Comment by Mythalar** [comment]
I will this afternoon !
Sorry if that's such a headache...

**Comment by Mythalar** [comment]
So I tested this new version as a crossblooded sorcerer with elemental fire/Gold dragon bloodlines.

Sadly the elemental focus/greater would not apply to spells other that fire based :'(

I choosed fire focus (+ greater) and cold focus (without greater) and, consistently with or without activating the elemental conversion, the DC of my spells would be :
- Base DC + 2 for fire spells
- Base DC + 1 for cold spells
- Base DC for all other spells

The bonus damage from gold dragon would still apply if any spell is converted to fire, as it should be.

**Comment by Truinto** [comment]
I had to dig really deep to figure out what's going on. Firstly, Tabletop-Tweaks also patches "IncreaseSpellDescriptorDC" which straight up swallows my code.
But even then, the context spell descriptor always get's overwritten with fire element. I don't yet know why.

**Comment by Truinto** [comment]
Pretty sure it works now.

**Comment by Mythalar** [comment]
Made all kind of tests and that works great for everything I could think of !

Only some side things like oracle revelations do not apply to converted spells but that's more min maxing there, and probably in line with rules...

Thank you very much :)
