### ISSUE TITLE
Request: Ascended Summons tweak

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#51]
Summons are pretty lack luster in this game cause of how bloated enemy stats are, and the mythic meant to make them better... doesnt really do its job

why not change it's effects from boosting ability scores to simpler untyped boosts to AC/Attack/Saves(plus the DR bypass)

the exact value of the boost stumps me tho, the vanilla is half mythic level boost to ability scores(basically meaning the real boost to AC/attack/Saves is 1/4 mythic level) so how about 5+mythic level? or 2xmythic level?

on a side note, im not sure if the mythic ability even affects undead summons(like animate dead, create undead, repurpose, etc since they arent technically summons) but the for the sake of gameplay i feel like this mythic definitely should so if it doesnt it would be a good idea to change it so it does.

**Comment by Truinto** [comment]
I increased the flat bonus to 5, so it's at least better than Augment Summoning. I added a feature that should convert and DR to N/-. Haven't playtested tho... should probably.
The minimum DR is 10 either way.
Not sure how to balance this. more than 10 to all ability scores sounds kinda busted.
