### ISSUE TITLE
Kineticists can always select Metal Blast and Blue Flame blast

### ISSUE THREAD

**Issue by aaronmaslen** [Truinto/DarkCodex#52]
Expanded Element selections appears to ignore the stated prerequisites in the description (Fire for Blue Flame and Earth for Metal). I can see that Kineticist.cs appears to add these prerequisites but they don't seem to be having any effect.

**Comment by Truinto** [comment]
Weird, I am sure I tested these. Perhaps you have Toybox's ignore prerequisite checked, no?
I will check at a later time. I reworked the project structure and need to finish before I can edit anything.

**Comment by aaronmaslen** [comment]
Prerequisites are working for other feats, so I don't think that's the problem but I'll see if I can investigate further.

**Comment by Truinto** [comment]
Done.
