### ISSUE TITLE
Request: Cursing gaze for sylvan trickster

### ISSUE THREAD

**Issue by veidral** [Truinto/DarkCodex#53]
Currently sylvan tricksters can´t select cursing gaze. 

It would be sweet if it was possible. 

Thanks.

**Comment by Truinto** [comment]
Is that on a trickster bonus list? I will check.

**Comment by veidral** [comment]
Yeah, the rogue archetype sylvan trickster gets hexes as part of rogue talents.

**Comment by Truinto** [comment]
Cursing Gaze is a mythic ability, not a hex. But I will make ice tomb available.

----------------------------------------

24.05.2022 17:41:06 veidral ***@***.***>:

**Comment by veidral** [comment]
Yes, cursing gaze is a mythic ability. What I´ve been trying to say is that it would be great if sylvan trickster could select it when picking mythic abilities since they have access to hexes.

**Comment by Truinto** [comment]
Oh... silly me. Will fix these three lists.

**Comment by Truinto** [comment]
Done.
