### ISSUE TITLE
Request: Boundless Healing work with Negative spells (Let me heal my Dhampir!)

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#55]
As above, I'd like to see a patch made available that makes Boundless Healing work with the negative energy spells. Maybe a bit unbalanced since it can be used to attack, but so can normal healing spells when around 1/3 of the enemies in the early game are undead.

**Comment by Truinto** [comment]
Sure, why not.

**Comment by Truinto** [comment]
Done.
