### ISSUE TITLE
3rd and 4th level healing spells are reversed

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#56]
Having Boundless healing is giving Cure Critical Wounds as a 3rd level spell (and with Boundless Injury, Inflict Critical), while giving Cure/Inflict Serious Wounds as a 4th level spell.

**Comment by FrijDom** [comment]
![image](https://user-images.githubusercontent.com/47518803/170412190-9434458e-51cc-48d2-8376-42d647b8c672.png)

**Comment by Truinto** [comment]
You are right, I mixed them up. I will update this. Note that this might not retroactively fix it for you without respec.

**Comment by FrijDom** [comment]
That's fine. I also noticed that a similar issue shows up with Restoration and Greater Restoration. They're 4th and 7th level spells, respectively, but your mod has them set as 3rd and 4th.

**Comment by Truinto** [comment]
Fixed

**Comment by Truinto** [comment]
Uh, I didn't notice the second message. will change that too.
