### ISSUE TITLE
Request(bug fix): Make "Aspect" spells work with Master Shapeshifter

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#58]
the mythic ability claims to work when polymorph'd, those spells* have the polymorph tags(as they do physically change the character's shape beyond just size, least in text) and yet dont work(despite smth as trivial as a kitsune's inate shapeshifting working with the ability)

feel like that should be addressed

*the spells in question, all tagged with polymorph already: 
Animal Aspect(+Greater version)
Frightful Aspect
Aspect of the Wolf
Aspect of the Bear
Aspect of the Falcon

1 extra 'issue' related to Master Shapeshifter is how the metamorph alchemist's Beast Shape doesnt benefit from the infinite use aspect of the ability, this can be argued to be intentional but imo its dumb

**Comment by Truinto** [comment]
I did that, but didn't play test. Let me know please.

**Comment by TKDancer** [comment]
doesnt seem to be working, no bonuses from having those spells on while having master shifter. did notice frigtful aspect is missing its polymorph tag now tho(which i think it had before, and should have according to TT)

**Comment by TKDancer** [comment]
also idk if you tried to also expand the infinite wildshape part to metamorph alchemist, but if you did its also not working

**Comment by Truinto** [comment]
SourceAbility was always null. I changed the check. It works now with any spell that has the polymorph descriptor.

**Comment by TKDancer** [comment]
frightful aspect is still missing the polymorph tag it should have and had in the past
