### ISSUE TITLE
Bugfix(?) Request: Swift Hunters Bond not applying/selectable to Freebooter

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#59]
(?) cause im not sure if this was intended or not, the mythic ability cant even be selected

they are technically separate and different abilities but supposed to be equivalents of the same class feature

**Comment by Truinto** [comment]
I think I fixed that. Didn't test, let me know if it's bugged.
Btw, yeah, it's a completely different feature and wouldn't normally apply. But it's in the homebrew category, so who cares ;)
