### ISSUE TITLE
Flensing strike not stacking. 

### ISSUE THREAD

**Issue by veidral** [Truinto/DarkCodex#60]
Hello, I´ve noticed that flensing strike doens´t stack with itself as it should according to the description. 
I´ve attached two screenshots with the attack rolls from two different attacks from the same attack sequence. 
You´ll notice that in the second screenshot, while it says -8 natural armor instead of -5 as in the first screenshot, the calculated ac is still 17. 

My first thought was that this was an interaction with Tabletoptweaks nonstacking natural armor option, but since I disabled it and the issue persists I doubt it. 

![1stattack](https://user-images.githubusercontent.com/60818651/171822184-f9fb73a5-e76a-4abf-87bc-49be38556363.png)
![2ndattack](https://user-images.githubusercontent.com/60818651/171822202-c41bc35f-e425-4772-a590-eca743ed0cfe.png)

**Comment by Truinto** [comment]
Found the issue. I increase the value, but didn't force an update to the stats. Fixed with next release.
