### ISSUE TITLE
Installing Problem 

### ISSUE THREAD

**Issue by RevanStarforge** [Truinto/DarkCodex#62]
Well, it was odd, when i downloaded your mod and installed it like i did every other mod, something weird happened. your mod showed up in the unity mod manager but it didnt said "OK", i right clicked it and pressed install again, nothing... i entered the game and dark codex is not on the mod list...

so i checked the game drectory/mod files and i noticed the contents of your mods are inside the mod folder, but they're all over the place, instead being inside their own folder. So i got around it by creating a folder "Dark Codex" and putting all those seperate files inside of it and it worked... but you might wanna perhaps check that..?

Also, since your mod introduces tons of logics ect... is this plays well with tabletop tweaks?

Thanks from another Demon Kineticist main for this beautiful mod

**Comment by Truinto** [comment]
Oh, that sounds bad. What version of unity mod manager do you use? I am pretty sure that didn't happen when I tried it.

I play with tabletop tweaks. Shouldn't be a problem. I haven't all options enabled, so if you find a bug let me know. Generally the bugs are just "x doesn't work and does nothing instead".

**Comment by RevanStarforge** [comment]
thanks my sibling in abyss, i look forward to use your mod with my eventual Re-play of Demon Kineticist with the Enhanced Edition. I'm anxious how it'll look already. also a small thing i noticed, that you're trying to give 'demon lord' abilities to the demon mythic path, and first idea you can come up with was to my understanding 'at will teleport' which is cool idea, but isnt that basically what demonic charge is? though, i certanly get the intent. and i just wanted say if i can think anything, i'll pots here or try to contact you for suggestion if you like.


as for unity manager...
when i open the unity mod manager it says there is no updates. and its says i have 0.24.0.0 ..? not sure it's the latest one but Dark Codex mod says it is fine with 0.23.0.0... so i'm not sure that's the issue

**Comment by Truinto** [comment]
Weird. Oh, perhaps you are an OSX user? Or are you using Windows?
Will be a pain to change my script to pack it another folder, but I guess I have to.

**Comment by Truinto** [comment]
Well, I never quite finished demon lord. This is basically just me role playing. The other demons can teleport at will, so I want that too :D

**Comment by RevanStarforge** [comment]
I'm using windows 10 yes


As for demons teleporting, yes, other demons can teleport at will, and you get an ability i think at the entry (3th level mythic path) called Demonic Charge, which is a teleportation WITH explode... And while normal teleport is standart action, demonic charge is move action, so it's even better... Just so you know... ^^


These are all the things EVERY demon has in pathfinder universe
- Immunity to electricity and poison.
- Resistance to acid 10, cold 10, and fire 10.
- Summon (Sp) Demons share the ability to summon others of their kind, typically another of their type or a small number of less powerful demons.
- Telepathy.
- Except where otherwise noted, demons speak Abyssal, Celestial, and Draconic.
- A demon’s natural weapons, as well as any weapon it wields, is treated as chaotic and evil for the purpose of resolving damage reduction

Most of these things gradually given by the demonic path. 

Telepathy is an issue because there is no possible use for it, it's sort of a story thing, you get to talk without moving your lips, it's cool, but yeah... story needs to recognize that, it's mostly a flavor ability, unless you're captured or gagged. Because most telepathy ranges are 100 ft... So you can't just make a call across continent. That is another ability/spell called Sending as you might now.


Giving Demon, Abyssal language also a story thing...


I think the weapon youre holding automatically considered chaotic and evil could be a thing... but then again, we don't fight many Lawful or Good creatures to bypass their DR... so... yeah... Demon Path is good at making you a demon.

**Comment by Truinto** [comment]
Yeah I know demon charge is great. It's also really flashy and doesn't look like any other demon teleport. You get the one all other demons use as a 4th level spell. But I didn't like to spend spell slots, so I have a patch that makes that one spell infinite (and swift). I never use it in combat, but it's cool for navigation out of combat.

I will check about the other stuff and how it could work ingame. I thought about granting a resurrection once per year, after you are a demon lord.
