### ISSUE TITLE
Request: Traits Half-Orc, Half-Elf

### ISSUE THREAD

**Issue by Truinto** [Truinto/DarkCodex#64]
### Via private message

<div type='discussions-op-text'>

<sup>Originally posted by **nielsdejong**</sup>

https://www.d20pfsrd.com/races/core-races/half-orc/
Orc Atavism: Some half-orcs have much stronger orc blood than human blood. Such half-orcs count as only half-orcs and orcs (not also humans) for any effect related to race. They gain a +2 bonus to Strength and a –2 penalty to one mental ability score of their choice. Finally, they gain the ferocity universal monster ability. This racial trait replaces the half-orc’s usual racial ability score modifiers, as well as intimidating, orc blood, and orc ferocity.

https://www.d20pfsrd.com/races/core-races/half-elf/
Kindred-Raised: While most think of people with one human and one elven parent when they think of half-elves, some half-elves are raised by two half-elven parents. Such half-elves feel less like outsiders, making them more confident, but less adaptable without the exposure to a human parent. They gain a +2 bonus to Charisma and one other ability score of their choice. This racial trait replaces the half-elf’s usual racial ability score modifiers, as well as adaptability, elven immunities, keen senses, and multitalented.

</div>

**Comment by Nielspeterdejong** [comment]
Good evening :) 

I'm sorry for the confusion, but the modifiers should be in addition to the +2 ability score of your choice. So basically it becomes:

Orc Atavism:

**Comment by Nielspeterdejong** [comment]
**Orc-Atavism -** Orc-Atavism half-orc loses keen senses and suffers a -2 racial penalty to Charisma, but gains Razortusk and a +2 racial bonus to Strength. Orc-Atavism half-orc keeps Orc Ferocity, Orc Weapon Familiarity, Intimidating, as well as a +2 bonus to one ability score of their choice.

**Comment by Nielspeterdejong** [comment]
The reason why my Orc-Atavism is different is because this is an alternative version that some groups have used, and I felt that this might be easier for you to implement instead of having to make an entirely updated Ferocity. Hence why I suggested going with this option.

**Comment by Nielspeterdejong** [comment]
This way you could for example choose Strength for your +2 ability score bonus as a Orc-Atavism half-orc, and gain a +4 bonus to Strength and a -2 penalty to Charisma. You could also choose Charisma for your +2 ability score, and end up with only a +2 Strength increase, but you'd exchange keen senses for the Razortusk feat: https://pathfinderwrathoftherighteous.wiki.fextralife.com/Razortusk

**Comment by Nielspeterdejong** [comment]
I hope that this makes more sense?

**Comment by Nielspeterdejong** [comment]
Ah alright :) And thanks for being willing to make my request! I think that a lot of people would love this option for their half-orc as well.

**Comment by Nielspeterdejong** [comment]
Also, for Kindred-Raised, you don't lose Elven Immunities with this mod and you can stack the charisma on top of one another like you can right now in vanilla, plus I don't think you have multi-talented in Wrath of the Righteous? (could be wrong). Plus with this alternative Orc-Avatism Racial Heritage you still count as human. In which case it should be:

Orc-Atavism: Some half-orcs have much stronger orc blood than human blood. They gain a +2 bonus to Strength and one ability score of their choice, and a –2 penalty to Charisma. Finally, they gain the Razortusk feat but lose keen senses.

Kindred-Raised: While most think of people with one human and one elven parent when they think of half-elves, some half-elves are raised by two half-elven parents. Such half-elves feel less like outsiders, making them more confident, but less adaptable without the exposure to a human parent. They gain a +2 bonus to Charisma and one ability score of their choice. This Racial Heritage replaces the half-elf’s usual racial ability score modifiers, as well as adaptability and keen senses.

Though for Wrath of the Righteous they call it Racial Heritages and kinda word it more like how I worded it in my first reply, see the wiki page here: https://pathfinderwrathoftherighteous.wiki.fextralife.com/Half-elf

And again, thanks so much for making this :)

**Comment by Nielspeterdejong** [comment]
Oh btw, what did you mean with ticket? As in a tab where we can discuss the details as well as a reminder? Just asking as I've never used Github :)

**Comment by Truinto** [comment]
I added this 2 weeks ago. I didn't have time to play test it. There is a mediocre chance it's not working at all. Would be great, if you would test it out.

**Comment by Truinto** [comment]
It's my bad, I didn't mention it. I thought I would be able to try it out, but time flies by so quickly. I called it 'ticket' for a lack of a better word. You can called it public forum, if you prefer that. I just despise Nexus for a multitude of reasons.

Anyway. Is this your first mod you installing? The front page has it covered https://github.com/Truinto/DarkCodex#installation

**Comment by Nielspeterdejong** [comment]
No problem :) And I have that actually, the unity mod, but I'm not sure where I have to click to download the mod itself?

**Comment by Nielspeterdejong** [comment]
This mod you made I mean, I'm afraid I'm not familiar with github, so I'm not sure which button to click to download this mod you made for me.

**Comment by Truinto** [comment]
![pic1](https://user-images.githubusercontent.com/47917181/175126699-948064b2-7e9d-47a7-9d6c-ede6e72c716e.png)
![pic2](https://user-images.githubusercontent.com/47917181/175126636-491d9aaf-1954-4037-b2b9-abb5db7a94bd.png)

**Comment by Nielspeterdejong** [comment]
Got it! Thanks, I'll go try it out :) And is this a mod that also involves my idea? So like a collection of mods right?

**Comment by Nielspeterdejong** [comment]
Alright, gonna test it now, thanks again! I will let you know how it goes.

**Comment by Nielspeterdejong** [comment]
Orc-Atavism: Some half-orcs have much stronger orc blood than human blood. They gain a +4 bonus to Strength, and a –2 penalty to Intelligence, Wisdom, or Charisma (your choice). Finally, they gain the Razortusk feat but lose keen senses.

**ALTERNATIVE**: If you are able to add in Ferocity, then you could change it as following: 
Orc-Atavism: Some half-orcs have much stronger orc blood than human blood. They gain a +2 bonus to Strength and a –2 penalty to one mental ability score of their choice. Finally, they gain the ferocity universal monster ability and Razortusk. This Racial Heritage replaces the half-orc’s usual racial ability score modifiers, as well as orc ferocity and keen senses.

Kindred-Raised: While most think of people with one human and one elven parent when they think of half-elves, some half-elves are raised by two half-elven parents. Such half-elves feel less like outsiders, making them more confident, but less adaptable without the exposure to a human parent. They gain a +2 bonus to Charisma and one ability score of their choice. This Racial Heritage replaces the half-elf’s usual racial ability score modifiers, as well as adaptability and keen senses.

**Comment by Nielspeterdejong** [comment]
However, if you are able to add in the Ferocity monster ability (which was also in Kingmaker: https://pathfinderkingmaker.fandom.com/wiki/Ferocity ) then I feel that the second option for Orc Atavism would be a lot more fitting! Half-orc players could choose to give up their +2 ability score increase and the keen senses trait for a better Ferocity trait as well as the Razortusk feat. Thus giving both options ups and downs.

**Comment by Nielspeterdejong** [comment]
Oh! And one final request: I looked at the other features and I think that all were really awesome ideas! But I would also love it if this idea for Orc Atavism could be a stand alone mod as well if that was possible? So that I can select to either use your entire mod or Orc Atavism as a stand alone mod. Would that be alright?

**Comment by Nielspeterdejong** [comment]
This stand alone mod could be called "Better Half Breeds" for example, which I think a lot of people would also like to have as a stand alone mod :)

**Comment by Nielspeterdejong** [comment]
Unfortunately the Ferocity trait still does not appear in character creation, nor in the game itself.

**Comment by Nielspeterdejong** [comment]
I made sure to remove the original mod, then download the newest version, but still no luck.

**Comment by Truinto** [comment]
I know. There is another bug. But it's purely visual. The feature is there and works, you just can't see it. I already told you this.

**Comment by Nielspeterdejong** [comment]
Ah alright, then everything is fine. Thank you again so much for making this :)

**Comment by Nielspeterdejong** [comment]
I just noticed that the description for Orc Atavism is not correct on the current version, as it mentions the a +2 increase to one ability score of your choice. Plus in WoTR there is no benefit to also counting as an orc. Could you change it to the following?

**Orc Atavism:** Some half-orcs have much stronger orc blood than human blood. They gain a +2 bonus to Strength and a –2 penalty to one mental ability score of their choice. Finally, they gain the ferocity universal monster ability. This racial trait replaces the half-orc’s usual racial ability score modifiers, as well as intimidating, and orc ferocity.

OR, if you are fine with going with my original idea, you could also give them +2 to one ability score of their choice on top of what they have right now, and make it as following:

**Orc Atavism:** Some half-orcs have stronger orc blood than human blood. They gain a +2 bonus to Strength, a +2 bonus to one ability score of their choice, and a –2 penalty to one mental ability score of their choice. Finally, they gain the ferocity universal monster ability. This racial trait replaces the half-orc’s usual racial ability score modifiers, as well as intimidating, and orc ferocity.

Again, the latter is entirely up to you, as it is your mod, but I feel that Orc Atavism could receive some love after my playtests.

**Comment by Nielspeterdejong** [comment]
Also, sorry for being so difficult with my request, as I’m really glad that you picked it up. But after playtesting them a bit I really feel that giving them the second option with +2 ability score of their choice (instead of the Razortusk feat) would be fair with the current drawbacks for this heritage.

**Comment by Truinto** [comment]
What are you even talking about? They already get +2 strength, +2 of their choice, and -2 of their choice.

![1](https://user-images.githubusercontent.com/47917181/178590905-29db1314-4341-4041-8465-74de627ac59f.png)

**Comment by Nielspeterdejong** [comment]
.... okay, forget everything I said. I'm an idiot, and I didn't see that part for some reason as I looked through the mod when I got back exhausted from work.

I'm really sorry about this. Honestly, this mod is now perfect! I should have seen this ages ago as well, but my half asleep brain from overworking couldn't register it. Sorry again for the troubles, and thank you again as well!

**Comment by Nielspeterdejong** [comment]
So I have playtested it, and it works perfectly! Ferocity even shows up in the character window. Thanks a ton for making this, and sorry again for my half asleep brain ^^;

**Comment by Nielspeterdejong** [comment]
Oh, but with the last change I would also change the description of Orc Atavism as follows:

Orc Atavism: Some half-orcs have stronger orc blood than human blood. They gain a +2 bonus to Strength, a +2 bonus to one ability score of their choice, and a –2 penalty to one mental ability score of their choice. They also gain razortusk. Finally, they gain the ferocity universal monster ability. This racial trait replaces the half-orc’s usual racial ability score modifiers, as well as intimidating, and orc ferocity.

After that, everything should be final like this.
