### ISSUE TITLE
Arcane apotheosis

### ISSUE THREAD

**Issue by syntaxdot** [Truinto/DarkCodex#65]
Hey, Truinto! 
Thanks a lot for implementing the feat into the game! 
Just wanted to give you a heads up: tried adding this feat via toy box, works perfectly, the only issue is that a saving error occurs when I try to save the game with this feat added. There's no issue when I remove this feat. 
And thanks again for your work!

**Comment by Truinto** [comment]
Fixed the saving issue :)

**Comment by syntaxdot** [comment]
Thank you so much!
