### ISSUE TITLE
Sacred summons

### ISSUE THREAD

**Issue by Truinto** [Truinto/DarkCodex#66]
https://www.d20pfsrd.com/feats/general-feats/sacred-summons/

Sacred Summons
The minions of your divine patrons stand ready to answer your call.
Prerequisites: Aura class feature, ability to cast summon monster.
Benefit: When using summon monster to summon creatures whose alignment subtype or subtypes exactly match your aura, you may cast the spell as a standard action instead of with a casting time of 1 round.

**Comment by RevanStarforge** [comment]
you can make the aura class feature as prerequisite for "cleric or paladin" i think
