### ISSUE TITLE
Issue: Impaling Infusion

### ISSUE THREAD

**Issue by ildesenesence** [Truinto/DarkCodex#68]
Appears to only work with earth blasts, currently have a water/water kineticist with impale selected who does not receive the button to activate the infusion

**Comment by Truinto** [comment]
The infusion is usable with earth, metal, and ice. Can you not use the ice impale variant?

**Comment by ildesenesence** [comment]
The option to "turn on" impale doesn't show up with ice blast.

**Comment by Truinto** [comment]
Please unfold the ice composite blast ability and screenshot the result for me.
Take care, the cold ability looks a lot like it, but is not compatible.

**Comment by Truinto** [comment]
I tested in on a character that's not a kineticist. If I add ice blast, elemental selection water, and impale, then the ability shows up. Could not find any bug.
