### ISSUE TITLE
Major Bug: Not working with patch 1.3.5e

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#69]
![bug](https://user-images.githubusercontent.com/35548194/172994168-f36a928f-e009-4dfb-a4d1-88143dc1ce74.png)

after the 1.3.5e patch(June 9th 2022) i cannot save(save error in dialogue box) and changing areas leads to me being booted to the main menu with that error message

player.log file:
[Player.log](https://github.com/Truinto/DarkCodex/files/8875922/Player.log)

**Comment by Truinto** [comment]
That's my bad. I already have the code fixed, but will need some time to push a release.
The culprit is lv20 arcane bloodline.

**Comment by TKDancer** [comment]
no rush!

**Comment by Truinto** [comment]
Fixed :)
