### ISSUE TITLE
Request: Make Brown-Fur Share Transmutation work with non-Arcanist spells

### ISSUE THREAD

**Issue by FrijDom** [Truinto/DarkCodex#70]
The description doesn't specify that it only works with arcanist spells, so I figure no reason it should be forced to. Let me use it with my sorcerer or wizard spell slots.

**Comment by Truinto** [comment]
Done. I fell into a trap. Doing this made it so using the Share Transmutation ability would be consumed by itself :D
Now it will only work on things that are specifically spells, not spell-like abilities.
