### ISSUE TITLE
Arcane Apotheosis still have a problem

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#71]
in v1.3.8，when i let ember have the Arcane Apotheosis(by the mythic power), her spell with metamagic still use a full round.
shall i respect the ember then take the power?

**Comment by knightddk** [comment]
ok,it works, if i want to use the new ability ,i neet to use toybox add the metamagic adept,the the  Arcane Apotheosis(by the mythic power) can work correctly

**Comment by Truinto** [comment]
This is really hard to read. Would you mind phrasing that again? Perhaps you have more success with a auto-translator.

**Comment by knightddk** [comment]
Sorry, I edited the comments too many times. Ember used Myth ability to get the Arcane Apotheosis(I retraining ember to the Sorcerer). It works when ember got it.But when I store the game and restart, ember's spell with metamagic feat still need Full-Round Action.

When I use toybox to remove Arcane Apotheosis then add it to ember, it works again. But when I restart the game or save/load, it doesn't work again.

**Comment by Truinto** [comment]
Fixed

**Comment by knightddk** [comment]
> Fixed
