### ISSUE TITLE
Bugfix: Return Frightful Aspect's Polymorph tag

### ISSUE THREAD

**Issue by TKDancer** [Truinto/DarkCodex#72]
not sure if this was changed in an owlcat patch or caused when you tried to fix master shapeshifter but the spell lost it's polymorph tag(which it should have according to TT)

seems to be messing with stacking rules too due to the missing descriptor

**Comment by Truinto** [comment]
Frightful Aspect has the polymorph descriptor and master shapeshifter does apply to it. Admittedly the spell's tooltip does not show any descriptors, but that's certainly not my fault.

**Comment by TKDancer** [comment]
weird i could swear in-game it used to have the descriptor in the tooltip in the past(i.e pre last patch) which allowed it to 'stack' with specific things(like legendary proportions), weird if owlcat themselves removed it

like my Cam has both effects on at the same time cause she had it pre patch but anyone else trying to do the same now has FA overwrite LP completely(i.e no FA for the aura while benefiting from LP's size bonuses to ability scores and AC instead)
