### ISSUE TITLE
Request: Arcanist Spontaneous Metamagicking and Spontaneous casting in general

### ISSUE THREAD

**Issue by RevanStarforge** [Truinto/DarkCodex#74]
So normally, Arcanist has two options to use metamagics... This was actualy possible in the call of the wilds mod for example in kingmaker, but as other things, i gues owlcat opted not to implement this thing.

Arcanist should be able to create a metamagiced version of a spell, and can be able to memorize that spell just like how a wizard/cleric ect do.

But Arcanist also should be able to on the fly add any metamagic he knows to any spell he prepared as long as he prepared that spell's normal version that day, by raising it's cast time to full action (except in the case of Quicken of course). Just like a Sorcerer or Oracle does basically.

Example; Arcanist capable of casting up to 2 level spells. He wants to add extended metamagic to the Shield spell he'll cast.
First option is to just like wizard, before resting create an extended shield spell in the spellbook, put it into level 2 slot, or;

Memorize normal (level 1) Shield spell that day, create a Metamagicked Version of the Shield spell on the spellbook as 2nd level spell, that spell immediately shows up in the second level castable spells now, because normal version of the spells is memorized that day, then cast this 2nd level Extended Shield spell as a full round action.

Also in same principle, Arcanist should be able to benefit from items that gives extra spells to the spontaneous casters.

So i THINK issue arives from arcanist spell book not entirely being counted as a spontaneous spellbook...

Long post but i wanted to be through as possible... 

Could you please, if you have time try to implement this? Thank you so much.

**Comment by Truinto** [comment]
This took way more effort than I thought. I didn't even know Arcanist is a thing. Pretty flexible class feature. And yes, weird exceptions. It's basically both a memorized and spontaneous spell book, at least in code.
I did manage to fully implement the spontaneous metamagic.

About the other thing, I don't know what you mean. Can you at least tell me the item's name? If it's too much trouble I will leave it at that. This was already enough work for one bug fix.

**Comment by Mythalar** [comment]
I guess the items here are the various rings such as [Red Salamander](url=https://pathfinderwrathoftherighteous.wiki.fextralife.com/Red+Salamander)

**Comment by RevanStarforge** [comment]
@Mythalar yes.

there are few more, i think one is necromancer themed one is cold themed... and one is lightning themed... or so i think... lightning themed one might be the gloves that make everything lightning, but yeah... they did not work on arcanist. i hoped after the spontaneous metamagic fix, now the list of arcanist counts as spontaneous and it works, but apperently not yet

**Comment by Truinto** [comment]
So, technically Red Salamander not working for Arcanist is RAW and RAI. Arcanist is a prepared spellcaster. Except pearls of powers wouldn't work for him, since the spell slots are never consumed.

But I am a generous GM. I added it so temporary learned spells can be used without preparing it. But I don't allow to also use spontaneous metamagic on these kind of spells.
