### ISSUE TITLE
Suggestion : Venom Speaker / Venom infusion

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#77]
Hey there !

Continued use of your mod(s), that is quite the life expander for kineticist (among others), the Chain is really cool 'o'

Was thinking about how to make them more "useful" insted of dumb big blaster and saw that the [Venom infusion](https://aonprd.com/KineticistTalentsDisplay.aspx?ItemName=Venom%20Infusion) would be really nice since it is a universal subtsance infusion and the sickened condition is a nice one (and not that easy to inflict).

I don't know if the [Greater version](https://aonprd.com/KineticistTalentsDisplay.aspx?ItemName=Venom%20Infusion,%20Greater) is also possible, but even without it it would be useful (or perhaps a set-in-stone one that only affect CON or DEX?)

The [Venom Speaker](https://aonprd.com/KineticistTalentsDisplay.aspx?ItemName=Venom%20Speaker) wild talent, which is required, could be altered to the same poison resistance/immunity of the alchemist instead of poison lore perhaps (useful even if not game changing in WotR since poisons are not everywhere).

**Comment by Truinto** [comment]
Added. But I didn't try out the poison. Let me know if there are any issues.

**Comment by Mythalar** [comment]
So many thanks, I'll test what I can!
