### ISSUE TITLE
Bug report : Venom Infusion (Greater)

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#80]
Yes so... :p 

No issue with venom infusion as of now, even with the Aether blast added by SpencerMycek.

But the poison of the greater one seems weird to me : if the target fails the fort save then the d2 CON damage is immediatly dealt but then one of three things happen : 

- the poison disappears immediatly,
- the poison is correctly applied but disappears on the next round withount any save roll in the log
- the poison is correctly applied, deals 0 CON damage on the next round and disappear without any log line/save roll

The two are nonetheless quite useful !

**Comment by Truinto** [comment]
Mh... I copied it from other poisons, but I guess I need to check again.

I don't know what you mean with non-armed attacks. You mean unarmed fists attacks? How in the world would an infusion apply to that...

**Comment by Truinto** [comment]
Ah, I didn't set restriction. I thought it would apply to all blasts then. But clearly it applies to just everything instead.

**Comment by Truinto** [comment]
Would you please check again. I think it works now.

**Comment by Mythalar** [comment]
So I ran some tests and, on the bright side :

- There are no more infusion on weapon/fist attacks
- The poison does not seems to disappear randomly anymore, the recurring save is displayed

On the down side : 

- The poison does not seem to have an icon on the enemy portait in TB mode (but it has one on the inspect sheet), more cosmetic thing,
- The poison still seems to deal 0 or 1 CON damage (at leats on the reoccuring damage that's for sure) each round instead of 1 or 2, so it can have no effect actually,
- The two infusions are no longer applied on telekinetic/force blast from SpencerMycek [KineticistExpandedElements](https://github.com/SpencerMycek/KineticistExpandedElements)) mod, but that woulb the consequence of the restriction change.

**Comment by Truinto** [comment]
I think new buffs are generally not visible in that view.
Are you sure about the damage? Losing 1 CON while having an odd value like 17 wouldn't have any effect.
I should be able to add other people's elements, if I know the guids.

**Comment by Truinto** [comment]
Could it be a difficulty setting? I don't see how it would deal anything but 1d2 damage.

**Comment by Mythalar** [comment]
I will look into this but I cannot see what would do this since it's set to normal.
I m also quite confused -_-

**Comment by Truinto** [comment]
I checked the game's code again. I use the preimplemented poison mechanic. It is more complicated than it has to. I will replace it with my own code which should do the trick.

**Comment by Mythalar** [comment]
Ok, I never really used any poison (spell) so far so did not see those issues before.

I found the greater infusion useful, but a tad sub par since one would need multiple round to have a penalty that would be equal to the "sickened" status, but when it deals 0 damage... :p 

I, for one, would just change it to 2 CON damage on fail fort save each round for 6 round, cured on 2 consecutive saves.

Or even better, since the ability score per raw, can be chosen : on fail fort save, each round for 6 round, 2 damage to STR or DEX or CON randomly, cured if 2 consecutive fort save.
This way the poison is more powerful but you cannot target a specific ability (certainly more difficult, and perhaps an issue if no STR or CON at all, IE undead?).

**Comment by Mythalar** [comment]
Your new iteration is really cool and, whatever you did by replacing the poison logic, that makes the log so much clearer with the d2 damage actually displayed.
The sickened state while poisonned is a nice balance change and the infusion can be applied to SpencerMycek blasts so it's perfect.

The only remaining thing, since I did not find any other bug so far, is that there is not any mention of the sickened state in the greater infusion, and the debuff is not displayed when inspecting enemy (but the penalties are applied in the inspect windows and in the detailed log of said enemy rolls).

Some big thanks for this one !
