### ISSUE TITLE
Kintesist blade doesn't count as a weapon for spellstrike

### ISSUE THREAD

**Issue by mccabefliam** [Truinto/DarkCodex#81]
I know this is a niche case, but I am running a build that relies on this interaction with dark kinetist trickster with a magus dip (gets a fill level 20 spell book from trickster). Would appreciate a fix so that spellstrike works with kinetic blades.

**Comment by mccabefliam** [comment]
Tested turning off attack of opportunity on whip and it seemed to fix it. Would be cool to have it on whip but no worries if not. Although it does also impact the charge action, and spells that attack on cast also.

**Comment by Truinto** [comment]
It affect them how?

**Comment by Truinto** [comment]
I read the rules again. It isn't allowed to combine spellstrike with kinetic blade. Kinetic blade requires the use of an attack action, not an action that makes an attack. That the same rule that prevents the use of vital strike to work with change.
Maybe you could use kinetic whip and have a swift spell afterwards work in tandem. But that's super rare setup and the game doesn't allow for it anyway.

About the other interactions, please specify how it's wrong.

**Comment by mccabefliam** [comment]
Fair enough. I was concerned because it didn't work with the game rules not pnp, but I think your interpretation is a good one. Anyhow, because the kinetic blade doesn't count as a weapon one can not use the charge action (requires a wielded weapon) nor deal damage with their blast when using bladded dash spell (it seems to just do a weak punch).

**Comment by Truinto** [comment]
I meant charge not change. Vital strike doesn't work with charge.
