### ISSUE TITLE
suggestion:Spell Perfection

### ISSUE THREAD

**Issue by knightddk** [Truinto/DarkCodex#83]
if it is not too much trouble, could you add this feat: Spell Perfection
Spell Perfection
You are unequaled at the casting of one particular spell.

Prerequisites: [Spellcraft]15 ranks, at least three [metamagic] feats.

Benefit: Pick one spell which you have the ability to cast. Whenever you cast that spell you may apply any one [metamagic] feat you have to that spell without affecting its level or, as long as the total modified level of the spell does not use a spell slot above 9th level. In addition, if you have other feats which allow you to apply a set numerical bonus to any aspect of this spell (such as [Spell Focus], [Spell Penetration], [Weapon Focus][ray], and so on), double the bonus granted by that feat when applied to this spell.

thanks a lot

**Comment by Truinto** [comment]
It's impossible to dynamically resolve what bonuses are from feats or if they are set numeric or not.

All feats need to be checked manually. Please write me a complete list of all the relevant feats. Do mythic feats count?

**Comment by knightddk** [comment]
well i think Mythic Feats are feats too and this is the list
Spell Focus
Greater Spell Focus
Spell Penetration
Greater Spell Penetration
weapon focus（Ray）
Greater weapon focus（Ray）
Spell Specialization

Spell Penetration (Mythic)
School Mastery(Mythic)
Expanded Arsenal(Mythic)
Spell Focus(Mythic)
Greater Spell Focus(Mythic)

**Comment by Mythalar** [comment]
It can be tricky but Elemental focus (+ greater) should be included too.

But Expanded Arsenal does not give any numercal bonus (but apply those of another school) ?

**Comment by Truinto** [comment]
It's WIP, but a good chunk should work already.

**Comment by knightddk** [comment]
thanks your work！

**Comment by Mythalar** [comment]
Hey !

Since this ticket is till opened so I ran some tests.

Everything relative to DC bonus was fine (either bonus to school or element) but there seems to be an issue regarding spell caster level.

I used different setup including Spell specialisation, Mastered school and Varisian tatoo (TableTopTweaks) and the bonus was not doubled.

Also I could not select Spell Perfection with Draconic feats (Gold Dragon, minor issue really), and could not select 3rd party spells such as Freezing sphere from [Tome of the Firebird](https://github.com/pheonix99/TomeOfTheFirebird).

Testing on challenging mode.

**Comment by Truinto** [comment]
Thanks for the feedback. Already found a bug and that TTT is changing stuff I do as well, making more bugs.
About Firebird, are these spells selectable in Spell Specialization? Because I copy that list.

**Comment by Mythalar** [comment]
None of the 3rd party spells (I think there are some from other mods) can be selected with spell specialization (nor with metamagic master, but I guess it's the same issue).

**Comment by Truinto** [comment]
Spell specialization, mastered school and varisian tattoo should be fixed. Picking 3rd party spells will work, if they can be picked by spell specialization. I told Vek about this issue.

**Comment by Mythalar** [comment]
Ok I'll test the fix

**Comment by Mythalar** [comment]
No more issue with spell perfection with the same tests as before ! 

Ok for the new spells.
