### ISSUE TITLE
melee weapon required

### ISSUE THREAD

**Issue by Tequilaman** [Truinto/DarkCodex#85]
Hi, for some reason keeps asking me this while trying to charge with kinetic blade as a kinetic knight. 

Not sure why, the weapon is already equipped.

**Comment by Truinto** [comment]
I make it so kinetic blade doesn't register as weapon for attacks of opportunity. Charge checks for such a weapon. I didn't know that.
If you activate whip infusion, it will work.

----------------------------------------

09.07.2022 19:15:01 Tequilaman ***@***.***>:

Hi, for some reason keeps asking me this while trying to charge with kinetic blade as a kinetic knight.

Not sure why, the weapon is already equipped.

**Comment by Truinto** [comment]
I make it so kinetic blade doesn't register as weapon for attacks of opportunity. Charge checks for such a weapon. I didn't know that.
If you activate whip infusion, it will work.

Will fix.

**Comment by Truinto** [comment]
No time to test. Does it work now?
