### ISSUE TITLE
Conflict with WotRResourceUnification

### ISSUE THREAD

**Issue by RobMatteson** [Truinto/DarkCodex#86]
Conflict with [WotRResourceUnification](https://github.com/pheonix99/WotRResourceUnification) breaks some of the Limitless mythic abilities. See the following for details:

https://github.com/pheonix99/WotRResourceUnification/issues/1#issue-1299806423

**Comment by pheonix99** [comment]
This is *NOT* a compatibiltiy issue.

ResourceUnification seems to have broken.

**Comment by pheonix99** [comment]
@Truinto Feel free to close, it appears something owlcat side broke my mod - uploading fix shortly.

**Comment by RobMatteson** [comment]
Version 1.2.0 of [WotRResourceUnification](https://github.com/pheonix99/WotRResourceUnification) fixes the issue.
