### ISSUE TITLE
Not getting freebie feats on MC

### ISSUE THREAD

**Issue by pheonix99** [Truinto/DarkCodex#9]
Exactly what it says - respeccing my Oracle to fix Annoying Curse Progression Problems and I don't have the freebie power attack anymore.

**Comment by TKDancer** [comment]
having same issue, using Barley's Respec mod(1.06.7)

**Comment by Truinto** [comment]
Got reported it may be related to "Better Backgrounds". Did not confirm yet.

**Comment by IcepickSR77** [comment]
> 
> 
> Got reported it may be related to "Better Backgrounds". Did not confirm yet.

I don't think so. I don't use "Better Backgrounds", but i get the same issue. Is there any information that would help you track it down?

**Comment by Truinto** [comment]
I have a test version that also checks for these feats whenever you level up. 'Badger' didn't have luck with it, but maybe it's worth a shot: https://github.com/Truinto/DarkCodex/tree/master/for-debug

**Comment by IcepickSR77** [comment]
> 
> 
> I have a test version that also checks for these feats whenever you level up. 'Badger' didn't have luck with it, but maybe it's worth a shot: https://github.com/Truinto/DarkCodex/tree/master/for-debug

Tried that with Respec (Version 1.09.2). Sadly did not work for me either.

**Comment by pheonix99** [comment]
Don't use Better Backgrounds either.

**Comment by Truinto** [comment]
I think it works now. Can't tell for sure as it always worked for me. Might be related on when the mod is first installed...
Please reopen, if the problem persists.
