### ISSUE TITLE
Arcanist spontaneous spells do not work Magical Supremacy

### ISSUE THREAD

**Issue by Red-Kai** [Truinto/DarkCodex#90]
Arcanist spontaneous spells cannot be cast with Magical Supremacy  arcane reservoir points , it also prevent metamagic spells be scribe as known spells (as a workaround)

**Comment by Truinto** [comment]
"Cannot be scribed as known spells" means you cannot prepare any metamagic spell. Is that correct? That would be a pretty big bug. I am surprised I didn't notice this.

**Comment by Red-Kai** [comment]
I stand corrected. You CAN scribe metamagic spells as long as its the only version of spell in the spellbook. For example you cannot jave regular version fireball together with empower fireball scribes. The original issue still exists, which is non scribes spell (spotenous metamagic) cannot be cast with arcane reservoir points .

**Comment by Truinto** [comment]
Took me forever to find the needle. Fixed.
