### ISSUE TITLE
Bug report : yet again Toxic infusion !

### ISSUE THREAD

**Issue by Mythalar** [Truinto/DarkCodex#91]
Ok I swear i do not do this on purpose !

So I tested greater toxic infusion multiple times and ran into the same bug each time : 
when the poison is applied, all target that fail the save are dealt 1d2 ability damages, which is right,
on each successive round all target that fail their save are dealt 1d2-1 ability damages, resulting in 0 or 1 damage at most

There are some screenshots from [first round](https://1drv.ms/u/s!AuHbZkjPDtRMhcgezdmVFCqZYv0rNQ?e=Cca8WS), and then [second](https://1drv.ms/u/s!AuHbZkjPDtRMhcgg7FX_8_3yHMJTjg?e=tgfBUf) (third was the same result, fourth too).

I cannot guess why :/

On the plus side the addition of poison icon in the interface is very helpful !

**Comment by Truinto** [comment]
As I said before, I think it's the difficulty setting. I checked the code and it will reduce it if damage to party is reduced. This is because the initiator is an enemy (I would have checked for target).

**Comment by Truinto** [comment]
I think I found a solution.

**Comment by Mythalar** [comment]
Oh ok i did not think of it this way, I ran most tests without changing any difficulty settings, and obviously did not understand that the enemy "deals damage to itself" with poison.

That's much more clear, and for my next tries I will at least remove the damage reduction...
It's even more counter intuitive that it changes from one round to the next (I guess it's because the first round the initiator is my MC directly)

**Comment by Mythalar** [comment]
Tested this with higher difficulty settings and no more poison damage reduction (until a very satisfying explosion if CON reduced to 0 ^^ ).

**Comment by Truinto** [comment]
I think it should recognize the source as the player now. If not, then I am out of ideas.

**Comment by Mythalar** [comment]
Tested it right now and the damage is still reduced with easiest settings but not with regular enemy damage.

Not an issue for me now that I know why !

Thanks for your time =)
