### ISSUE TITLE
Kinetic Blade (Kinetik Knight) Chosen Weapon for Sword Saint

### ISSUE THREAD

**Issue by solaris232** [Truinto/DarkCodex#95]
As an addendum to the Sword Saint my choose any weapon, would it be possible to have it include the Kinetic Blade from a Kinetic Knight? (I suppose that would mean Kinetic Blast being added to the list)

**Comment by Truinto** [comment]
There are no further checks. Are you sure it's not already there?

**Comment by SpencerMycek** [comment]
With the "any weapon for sword saint" on, yes. you can choose kinetic blade. One issue I'm trying to figure out:

Kinetic Blast doesn't seem to work with SpellStrike. It does with SpellCombat, thought.

You cast spell, get an extra weapon attack, but when that attack hits, the spell's effect does not go off

**Comment by SpencerMycek** [comment]
Let me amend that. It appears to work sort of with my custom blades, I guess theyre not exactly like the vanilla game ones.

Sometimes they don't deal damage, sometimes they do.
It seems for the vanilla kinetic blades, spellstrike doesn't trigger the KineticBlade damage ability to go off

**Comment by Truinto** [comment]
> Spellstrike: ... casts a spell with a range of “touch” from the magus spell list ...

Eh yeah, Kinetic Blade is not a magus spell. And no, the kinetic weapon should not be able to count as the weapon either. 

> Kinetic blade: You can use this form infusion once as part of an attack action, a charge action, or a full-attack action in order to make melee attacks with your kinetic blade.
> Spellstrike: Instead of the free melee touch attack normally allowed to deliver the spell, a magus can make one free melee attack with his weapon (at his highest base attack bonus) as part of casting this spell.

In other words, spellstrike is casting a spell and grants an attack. This is not an attack 'action', which is listed in the combat section as a specific standard action. This is same discussion as Vital Strike + Charge (or Spring Attack). See FAQ https://paizo.com/paizo/faq/v5748nruor1fm#v5748eaic9pyy

Of course you can homebrew this any way you want. I can't think of a reason why some would work and some not...

**Comment by Truinto** [comment]
Slight correction. If you use both Spell Combat and Spellstrike in conjunction, you might be able to use it with Kinetic Blade, even RAW. I am not sure.

**Comment by SpencerMycek** [comment]
I've seen it ruled either way, I didn;t know if you had intended it to work one way or the other. No worries and thank you!

**Comment by Truinto** [comment]
I pulled a little rules lawyer. Sorry :P 
In this case I would rule whatever is easier to code. But it should be consistent and not work with half of the time.
