### ISSUE TITLE
Suggestion: Tabletopish Spell Range

### ISSUE THREAD

**Issue by Nerin3** [Truinto/DarkCodex#96]
I know it might not be a good idea for a balancing purposes, but an option to modify range of spells yourself or (at least add those bonuses per level) would be nice, since some spells have ridiculously short range (I'm looking at you Entangle) and you can't cast them without being in their range yourself.

![image](https://user-images.githubusercontent.com/1911661/180771714-fa8e60a4-d561-4ad4-8dec-c3ff05d1a6ea.png)

**Comment by Truinto** [comment]
I added spell range which scales with level. Pretty ridiculous with my level 23 caster. Does not scale with racial spell-likes, spells with fixed or special range, or spells from classes that don't technically have caster levels (looking at kineticist).
