### ISSUE TITLE
Bug: Blade Whirlwind not using Kinetic Blade

### ISSUE THREAD

**Issue by SpencerMycek** [Truinto/DarkCodex#97]
Hello!
In doing some testing and messing around, I noticed that, with DarkCodex, the Blade Whirlwind Infusion did not trigger any attacks.
I also tested with Improved Unarmed Strike on the character, and it did trigger the attack, but with an unarmed strike instead of kinetic blade

I tested both with the Kinetic Whip infusion toggled, and both times, I got attacks from the kinetic blade.

This may be similar to this issue: #85 
Where marking a Kinetic Blade as unable to do Attacks of Opportunity has stopped it from working with Blade Whirlwind, and using Kinetic Whip (enabling AoO) makes it work correctly

**Comment by Truinto** [comment]
It is. Will patch a different function to fix all remaining interactions.

**Comment by SpencerMycek** [comment]
Thank you!

**Comment by Truinto** [comment]
I changed the patches. I tested that blade whirlwind does work without kinetic whip. I did not test that the interactions with attacks of opportunity still work.

**Comment by SpencerMycek** [comment]
Oh hey, forgot to post the validation. Yes, everything appears to be working now (As far as I can tell). And I haven't had any weirdness with AoO and kinetic blades (played from Act 1-4 with no issues)

**Comment by Truinto** [comment]
Thanks for the reply. I should have tested this, but I always forget.
